<?php
// This script and data application were generated by AppGini 5.97
// Download AppGini for free from https://bigprof.com/appgini/download/

/*
	ajax-callable script that returns code for either a combo drop-down or an auto-complete
	drop-down, based on number of items.

	REQUEST parameters:
	===============
	t: table name
	f: lookup field name
	id: selected id
	p: page number (default = 1)
	s: search term
	o: 0 (default) for text-only or 1 for full options list
	text: selected text
	filterer_[filterer]: name of filterer field to be used to filter the drop-down contents
				must be one of the filteres defined for the concerned field
*/

	$start_ts = microtime(true);

	// how many results to return per call, in case of json output
	$results_per_page = 50;

	$curr_dir = dirname(__FILE__);
	include_once("$curr_dir/lib.php");

	handle_maintenance();

	// drop-downs config
	$lookups = array(
		'pqr' => array(
			'barrio' => array(
				'parent_table' => 'barrios',
				'parent_pk_field' => 'nombre',
				'parent_caption' => '`barrios`.`nombre`',
				'parent_from' => '`barrios` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => true
			),
			'regimen' => array(
				'parent_table' => 'regimenes',
				'parent_pk_field' => 'nombre',
				'parent_caption' => '`regimenes`.`nombre`',
				'parent_from' => '`regimenes` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => true
			),
			'eps' => array(
				'parent_table' => 'eps',
				'parent_pk_field' => 'razonsocial',
				'parent_caption' => '`eps`.`razonsocial`',
				'parent_from' => '`eps` LEFT JOIN `regimenes` as regimenes1 ON `regimenes1`.`nombre`=`eps`.`regimen` ',
				'filterers' => array('regimen' => 'regimen'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => true
			),
			'gerente' => array(
				'parent_table' => 'eps',
				'parent_pk_field' => 'razonsocial',
				'parent_caption' => '`eps`.`gerente`',
				'parent_from' => '`eps` LEFT JOIN `regimenes` as regimenes1 ON `regimenes1`.`nombre`=`eps`.`regimen` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'teleps' => array(
				'parent_table' => 'eps',
				'parent_pk_field' => 'razonsocial',
				'parent_caption' => '`eps`.`telefono`',
				'parent_from' => '`eps` LEFT JOIN `regimenes` as regimenes1 ON `regimenes1`.`nombre`=`eps`.`regimen` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'maileps' => array(
				'parent_table' => 'eps',
				'parent_pk_field' => 'razonsocial',
				'parent_caption' => '`eps`.`correo`',
				'parent_from' => '`eps` LEFT JOIN `regimenes` as regimenes1 ON `regimenes1`.`nombre`=`eps`.`regimen` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'cc2' => array(
				'parent_table' => 'eps',
				'parent_pk_field' => 'razonsocial',
				'parent_caption' => '`eps`.`correo2`',
				'parent_from' => '`eps` LEFT JOIN `regimenes` as regimenes1 ON `regimenes1`.`nombre`=`eps`.`regimen` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'cc3' => array(
				'parent_table' => 'eps',
				'parent_pk_field' => 'razonsocial',
				'parent_caption' => '`eps`.`correo3`',
				'parent_from' => '`eps` LEFT JOIN `regimenes` as regimenes1 ON `regimenes1`.`nombre`=`eps`.`regimen` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'motivo' => array(
				'parent_table' => 'motivos',
				'parent_pk_field' => 'motivo',
				'parent_caption' => '`motivos`.`motivo`',
				'parent_from' => '`motivos` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => true
			),
			'obmotivo' => array(
				'parent_table' => 'obmotivos',
				'parent_pk_field' => 'observacion',
				'parent_caption' => '`obmotivos`.`observacion`',
				'parent_from' => '`obmotivos` LEFT JOIN `motivos` as motivos1 ON `motivos1`.`motivo`=`obmotivos`.`motivo` ',
				'filterers' => array('motivo' => 'motivo'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => true
			),
			'servicio' => array(
				'parent_table' => 'ips',
				'parent_pk_field' => 'nombre',
				'parent_caption' => '`ips`.`nombre`',
				'parent_from' => '`ips` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => true
			),
			'enfermedad' => array(
				'parent_table' => 'cie10',
				'parent_pk_field' => 'cie10',
				'parent_caption' => 'IF(CHAR_LENGTH(`cie10`.`cie10`) || CHAR_LENGTH(`cie10`.`descripcion`), CONCAT_WS(\'\', `cie10`.`cie10`, \' - \', `cie10`.`descripcion`), \'\')',
				'parent_from' => '`cie10` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => true
			),
		),
		'Encuesta' => array(
			'eps' => array(
				'parent_table' => 'eps',
				'parent_pk_field' => 'razonsocial',
				'parent_caption' => '`eps`.`razonsocial`',
				'parent_from' => '`eps` LEFT JOIN `regimenes` as regimenes1 ON `regimenes1`.`nombre`=`eps`.`regimen` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => true
			),
			'ipsprim' => array(
				'parent_table' => 'ips',
				'parent_pk_field' => 'nombre',
				'parent_caption' => '`ips`.`nombre`',
				'parent_from' => '`ips` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
		),
		'barrios' => array(
		),
		'soportes' => array(
			'doc' => array(
				'parent_table' => 'pqr',
				'parent_pk_field' => 'id',
				'parent_caption' => '`pqr`.`doc`',
				'parent_from' => '`pqr` LEFT JOIN `barrios` as barrios1 ON `barrios1`.`nombre`=`pqr`.`barrio` LEFT JOIN `regimenes` as regimenes1 ON `regimenes1`.`nombre`=`pqr`.`regimen` LEFT JOIN `eps` as eps1 ON `eps1`.`razonsocial`=`pqr`.`eps` LEFT JOIN `eps` as eps2 ON `eps2`.`razonsocial`=`pqr`.`cc2` LEFT JOIN `eps` as eps3 ON `eps3`.`razonsocial`=`pqr`.`cc3` LEFT JOIN `motivos` as motivos1 ON `motivos1`.`motivo`=`pqr`.`motivo` LEFT JOIN `obmotivos` as obmotivos1 ON `obmotivos1`.`observacion`=`pqr`.`obmotivo` LEFT JOIN `ips` as ips1 ON `ips1`.`nombre`=`pqr`.`servicio` LEFT JOIN `cie10` as cie101 ON `cie101`.`cie10`=`pqr`.`enfermedad` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
		),
		'eps' => array(
			'regimen' => array(
				'parent_table' => 'regimenes',
				'parent_pk_field' => 'nombre',
				'parent_caption' => '`regimenes`.`nombre`',
				'parent_from' => '`regimenes` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
		),
		'motivos' => array(
		),
		'obmotivos' => array(
			'motivo' => array(
				'parent_table' => 'motivos',
				'parent_pk_field' => 'motivo',
				'parent_caption' => '`motivos`.`motivo`',
				'parent_from' => '`motivos` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
		),
		'cie10' => array(
		),
		'ips' => array(
		),
		'mails' => array(
		),
		'covid' => array(
			'regimen' => array(
				'parent_table' => 'regimenes',
				'parent_pk_field' => 'nombre',
				'parent_caption' => '`regimenes`.`nombre`',
				'parent_from' => '`regimenes` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'eps' => array(
				'parent_table' => 'eps',
				'parent_pk_field' => 'razonsocial',
				'parent_caption' => '`eps`.`razonsocial`',
				'parent_from' => '`eps` LEFT JOIN `regimenes` as regimenes1 ON `regimenes1`.`nombre`=`eps`.`regimen` ',
				'filterers' => array('regimen' => 'regimen'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => true
			),
			'cual' => array(
				'parent_table' => 'cie10',
				'parent_pk_field' => 'cie10',
				'parent_caption' => 'IF(CHAR_LENGTH(`cie10`.`cie10`) || CHAR_LENGTH(`cie10`.`descripcion`), CONCAT_WS(\'\', `cie10`.`cie10`, \' - \', `cie10`.`descripcion`), \'\')',
				'parent_from' => '`cie10` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
		),
		'regimenes' => array(
		),
		'otros' => array(
			'barrio' => array(
				'parent_table' => 'barrios',
				'parent_pk_field' => 'nombre',
				'parent_caption' => '`barrios`.`nombre`',
				'parent_from' => '`barrios` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => true
			),
			'regimen' => array(
				'parent_table' => 'regimenes',
				'parent_pk_field' => 'nombre',
				'parent_caption' => '`regimenes`.`nombre`',
				'parent_from' => '`regimenes` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => true
			),
			'eapb' => array(
				'parent_table' => 'eps',
				'parent_pk_field' => 'razonsocial',
				'parent_caption' => '`eps`.`razonsocial`',
				'parent_from' => '`eps` LEFT JOIN `regimenes` as regimenes1 ON `regimenes1`.`nombre`=`eps`.`regimen` ',
				'filterers' => array('regimen' => 'regimen'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => true
			),
			'gerente' => array(
				'parent_table' => 'eps',
				'parent_pk_field' => 'razonsocial',
				'parent_caption' => '`eps`.`gerente`',
				'parent_from' => '`eps` LEFT JOIN `regimenes` as regimenes1 ON `regimenes1`.`nombre`=`eps`.`regimen` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
		),
		'prass' => array(
			'regimen' => array(
				'parent_table' => 'regimenes',
				'parent_pk_field' => 'nombre',
				'parent_caption' => '`regimenes`.`nombre`',
				'parent_from' => '`regimenes` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => false
			),
			'eps' => array(
				'parent_table' => 'eps',
				'parent_pk_field' => 'razonsocial',
				'parent_caption' => '`eps`.`razonsocial`',
				'parent_from' => '`eps` LEFT JOIN `regimenes` as regimenes1 ON `regimenes1`.`nombre`=`eps`.`regimen` ',
				'filterers' => array('regimen' => 'regimen'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => true
			),
		),
		'oportunidad' => array(
			'regimen' => array(
				'parent_table' => 'regimenes',
				'parent_pk_field' => 'nombre',
				'parent_caption' => '`regimenes`.`nombre`',
				'parent_from' => '`regimenes` ',
				'filterers' => array(),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => true
			),
			'eps' => array(
				'parent_table' => 'eps',
				'parent_pk_field' => 'razonsocial',
				'parent_caption' => '`eps`.`razonsocial`',
				'parent_from' => '`eps` LEFT JOIN `regimenes` as regimenes1 ON `regimenes1`.`nombre`=`eps`.`regimen` ',
				'filterers' => array('regimen' => 'regimen'),
				'custom_query' => '',
				'inherit_permissions' => false,
				'list_type' => 0,
				'not_null' => true
			),
		),
	);

	// XSS prevention
	$xss = new CI_Input(datalist_db_encoding);

	// receive and verify user input
	$table_name = $_REQUEST['t'];
	$field_name = $_REQUEST['f'];
	$search_id = makeSafe(from_utf8($_REQUEST['id']));
	$selected_text = from_utf8($_REQUEST['text']);
	$returnOptions = ($_REQUEST['o'] == 1 ? true : false);
	$page = intval($_REQUEST['p']);
	if($page < 1)  $page = 1;
	$skip = $results_per_page * ($page - 1);
	$search_term = makeSafe(from_utf8($_REQUEST['s']));

	if(!isset($lookups[$table_name][$field_name])) die('{ "error": "Invalid table or field." }');

	// can user access the requested table?
	$perm = getTablePermissions($table_name);
	if(!$perm['access'] && !$search_id) die('{ "error": "' . addslashes($Translation['tableAccessDenied']) . '" }');

	$field = $lookups[$table_name][$field_name];

	$wheres = [];

	// search term provided?
	if($search_term) {
		$wheres[] = "{$field['parent_caption']} like '%{$search_term}%'";
	}

	// any filterers specified?
	if(is_array($field['filterers'])) {
		foreach($field['filterers'] as $filterer => $filterer_parent) {
			$get = (isset($_REQUEST["filterer_{$filterer}"]) ? $_REQUEST["filterer_{$filterer}"] : false);
			if($get) {
				$wheres[] = "`{$field['parent_table']}`.`$filterer_parent`='" . makeSafe($get) . "'";
			}
		}
	}

	// inherit permissions?
	if($field['inherit_permissions']) {
		$inherit = permissions_sql($field['parent_table']);
		if($inherit === false && !$search_id) die($Translation['tableAccessDenied']);

		if($inherit['where']) $wheres[] = $inherit['where'];
		if($inherit['from']) $field['parent_from'] .= ", {$inherit['from']}";
	}

	// single value?
	if($field['list_type'] != 2 && $search_id) {
		$wheres[] = "`{$field['parent_table']}`.`{$field['parent_pk_field']}`='{$search_id}'";
	}

	if(count($wheres)) {
		$where = 'WHERE ' . implode(' AND ', $wheres);
	}

	// define the combo and return the code
	$combo = new DataCombo;
	if($field['custom_query']) {
		$qm = []; $custom_where = ''; $custom_order_by = '2';
		$combo->Query = $field['custom_query'];

		if(preg_match('/ order by (.*)$/i', $combo->Query, $qm)) {
			$custom_order_by = $qm[1];
			$combo->Query = preg_replace('/ order by .*$/i', '', $combo->Query);
		}

		if(preg_match('/ where (.*)$/i', $combo->Query, $qm)) {
			$custom_where = $qm[1];
			$combo->Query = preg_replace('/ where .*$/i', '', $combo->Query);
		}

		if($where && $custom_where) {
			$combo->Query .=  " {$where} AND ({$custom_where}) ORDER BY {$custom_order_by}";
		} elseif($custom_where) {
			$combo->Query .=  " WHERE {$custom_where} ORDER BY {$custom_order_by}";
		} else {
			$combo->Query .=  " {$where} ORDER BY {$custom_order_by}";
		}

		$query_match = [];
		preg_match('/select (.*) from (.*)$/i', $combo->Query, $query_match);

		if(isset($query_match[2])) {
			$count_query = "SELECT count(1) FROM {$query_match[2]}";
		} else {
			$count_query = '';
		}
	} else {
		$combo->Query = "SELECT " . ($field['inherit_permissions'] ? 'DISTINCT ' : '') . "`{$field['parent_table']}`.`{$field['parent_pk_field']}`, {$field['parent_caption']} FROM {$field['parent_from']} {$where} ORDER BY 2";
		$count_query = "SELECT count(1) FROM {$field['parent_from']} {$where}";
	}
	$combo->table = $table_name;
	$combo->parent_table = $field['parent_table'];
	$combo->SelectName = $field_name;
	$combo->ListType = $field['list_type'];
	if($search_id) {
		$combo->SelectedData = $search_id;
	} elseif($selected_text) {
		$combo->SelectedData = getValueGivenCaption($combo->Query, $selected_text);
	}

	if($field['list_type'] == 2) {
		$combo->Render();
		$combo->HTML = str_replace('<select ', '<select onchange="' . $field_name . '_changed();" ', $combo->HTML);

		// return response
		if($returnOptions) {
			?><span id="<?php echo $field_name; ?>-combo-list"><?php echo $combo->HTML; ?></span><?php
		} else {
			?>
				<span id="<?php echo $field_name; ?>-match-text"><?php echo $combo->MatchText; ?></span>
				<input type="hidden" id="<?php echo $field_name; ?>" value="<?php echo html_attr($combo->SelectedData); ?>">
			<?php
		}
	} else {
		/* return json */
		header('Content-type: application/json');

		if(!preg_match('/ limit .+/i', $combo->Query)) {
			if(!$search_id) $combo->Query .= " LIMIT {$skip}, {$results_per_page}";
			if($search_id) $combo->Query .= " LIMIT 1";
		}

		$prepared_data = [];

		// specific caption provided and list_type is not radio?
		if(!$search_id && $selected_text) {
			$search_id = getValueGivenCaption($combo->Query, $selected_text);
			if($search_id) $prepared_data[] = array('id' => to_utf8($search_id), 'text' => to_utf8($xss->xss_clean($selected_text)));
		} else {
			/*
			 * in case we have a search term, show matches starting with it first,
			 * followed by those containing it.
			 * build a UNION query for that purpose
			 */
			if($search_term) {
				$query2 = $combo->Query;
				$query1 = str_replace(" like '%{$search_term}%'", " like '{$search_term}%'", $query2);
				$combo->Query = "({$query1}) UNION ({$query2})";
			}

			$eo = ['silentErrors' => true];

			$res = sql($combo->Query, $eo);
			while($row = db_fetch_row($res)) {
				if(empty($prepared_data) && $page == 1 && !$search_id && !$field['not_null']) {
					$prepared_data[] = array('id' => empty_lookup_value, 'text' => to_utf8("<{$Translation['none']}>"));
				}

				$prepared_data[] = array('id' => to_utf8($row[0]), 'text' => to_utf8($xss->xss_clean($row[1])));
			}
		}

		if(empty($prepared_data)) { $prepared_data[] = array('id' => '', 'text' => to_utf8($Translation['No matches found!'])); }

		echo json_encode(array(
			'results' => $prepared_data,
			'more' => (@db_num_rows($res) >= $results_per_page),
			'elapsed' => round(microtime(true) - $start_ts, 3)
		));
	}

