<?php
// This script and data application were generated by AppGini 5.97
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir = dirname(__FILE__);
	include_once("{$currDir}/lib.php");
	@include_once("{$currDir}/hooks/barrios.php");
	include_once("{$currDir}/barrios_dml.php");

	// mm: can the current member access this page?
	$perm = getTablePermissions('barrios');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'barrios';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`barrios`.`nombre`" => "nombre",
		"`barrios`.`comuna`" => "comuna",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => 1,
		2 => 2,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`barrios`.`nombre`" => "nombre",
		"`barrios`.`comuna`" => "comuna",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`barrios`.`nombre`" => "Nombre",
		"`barrios`.`comuna`" => "Comuna",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`barrios`.`nombre`" => "nombre",
		"`barrios`.`comuna`" => "comuna",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`barrios` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = (getLoggedAdmin() !== false);
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'barrios_view.php';
	$x->RedirectAfterInsert = 'barrios_view.php?SelectedID=#ID#';
	$x->TableTitle = 'Barrios';
	$x->TableIcon = 'resources/table_icons/home_page.png';
	$x->PrimaryKey = '`barrios`.`nombre`';

	$x->ColWidth = [150, 150, ];
	$x->ColCaption = ['Nombre', 'Comuna', ];
	$x->ColFieldName = ['nombre', 'comuna', ];
	$x->ColNumber  = [1, 2, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/barrios_templateTV.html';
	$x->SelectedTemplate = 'templates/barrios_templateTVS.html';
	$x->TemplateDV = 'templates/barrios_templateDV.html';
	$x->TemplateDVP = 'templates/barrios_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: barrios_init
	$render = true;
	if(function_exists('barrios_init')) {
		$args = [];
		$render = barrios_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: barrios_header
	$headerCode = '';
	if(function_exists('barrios_header')) {
		$args = [];
		$headerCode = barrios_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once("{$currDir}/header.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/header.php");
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: barrios_footer
	$footerCode = '';
	if(function_exists('barrios_footer')) {
		$args = [];
		$footerCode = barrios_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once("{$currDir}/footer.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/footer.php");
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
