<?php
// This script and data application were generated by AppGini 5.97
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir = dirname(__FILE__);
	include_once("{$currDir}/lib.php");
	@include_once("{$currDir}/hooks/cie10.php");
	include_once("{$currDir}/cie10_dml.php");

	// mm: can the current member access this page?
	$perm = getTablePermissions('cie10');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'cie10';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`cie10`.`cie10`" => "cie10",
		"`cie10`.`descripcion`" => "descripcion",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => 1,
		2 => 2,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`cie10`.`cie10`" => "cie10",
		"`cie10`.`descripcion`" => "descripcion",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`cie10`.`cie10`" => "Cie10",
		"`cie10`.`descripcion`" => "Descripcion",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`cie10`.`cie10`" => "cie10",
		"`cie10`.`descripcion`" => "descripcion",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`cie10` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = (getLoggedAdmin() !== false);
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'cie10_view.php';
	$x->RedirectAfterInsert = 'cie10_view.php?SelectedID=#ID#';
	$x->TableTitle = 'CIE10';
	$x->TableIcon = 'resources/table_icons/pill_go.png';
	$x->PrimaryKey = '`cie10`.`cie10`';

	$x->ColWidth = [150, 150, ];
	$x->ColCaption = ['Cie10', 'Descripcion', ];
	$x->ColFieldName = ['cie10', 'descripcion', ];
	$x->ColNumber  = [1, 2, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/cie10_templateTV.html';
	$x->SelectedTemplate = 'templates/cie10_templateTVS.html';
	$x->TemplateDV = 'templates/cie10_templateDV.html';
	$x->TemplateDVP = 'templates/cie10_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: cie10_init
	$render = true;
	if(function_exists('cie10_init')) {
		$args = [];
		$render = cie10_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: cie10_header
	$headerCode = '';
	if(function_exists('cie10_header')) {
		$args = [];
		$headerCode = cie10_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once("{$currDir}/header.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/header.php");
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: cie10_footer
	$footerCode = '';
	if(function_exists('cie10_footer')) {
		$args = [];
		$footerCode = cie10_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once("{$currDir}/footer.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/footer.php");
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
