<?php
// This script and data application were generated by AppGini 5.97
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir = dirname(__FILE__);
	include_once("{$currDir}/lib.php");
	@include_once("{$currDir}/hooks/covid.php");
	include_once("{$currDir}/covid_dml.php");

	// mm: can the current member access this page?
	$perm = getTablePermissions('covid');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'covid';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`covid`.`id`" => "id",
		"if(`covid`.`fecha`,date_format(`covid`.`fecha`,'%d/%m/%Y'),'')" => "fecha",
		"`covid`.`tipodoc`" => "tipodoc",
		"`covid`.`doc`" => "doc",
		"`covid`.`nombre`" => "nombre",
		"`covid`.`genero`" => "genero",
		"if(`covid`.`nacimiento`,date_format(`covid`.`nacimiento`,'%d/%m/%Y'),'')" => "nacimiento",
		"`covid`.`edad`" => "edad",
		"`covid`.`telefono`" => "telefono",
		"IF(    CHAR_LENGTH(`regimenes1`.`nombre`), CONCAT_WS('',   `regimenes1`.`nombre`), '') /* Regimen */" => "regimen",
		"IF(    CHAR_LENGTH(`eps1`.`razonsocial`), CONCAT_WS('',   `eps1`.`razonsocial`), '') /* EPS */" => "eps",
		"`covid`.`embarazo`" => "embarazo",
		"concat('<i class=\"glyphicon glyphicon-', if(`covid`.`patologia`, 'check', 'unchecked'), '\"></i>')" => "patologia",
		"concat('<i class=\"glyphicon glyphicon-', if(`covid`.`fallecido`, 'check', 'unchecked'), '\"></i>')" => "fallecido",
		"IF(    CHAR_LENGTH(`cie101`.`cie10`) || CHAR_LENGTH(`cie101`.`descripcion`), CONCAT_WS('',   `cie101`.`cie10`, ' - ', `cie101`.`descripcion`), '') /* Cual? */" => "cual",
		"`covid`.`atencion`" => "atencion",
		"`covid`.`tratamiento`" => "tratamiento",
		"`covid`.`medicamentos`" => "medicamentos",
		"`covid`.`vigilancia`" => "vigilancia",
		"`covid`.`percepcion`" => "percepcion",
		"concat('<i class=\"glyphicon glyphicon-', if(`covid`.`medicinageneral`, 'check', 'unchecked'), '\"></i>')" => "medicinageneral",
		"`covid`.`oportunidad`" => "oportunidad",
		"`covid`.`observacion`" => "observacion",
		"`covid`.`status`" => "status",
		"`covid`.`responsable`" => "responsable",
		"`covid`.`periodo`" => "periodo",
		"`covid`.`asignado`" => "asignado",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`covid`.`id`',
		2 => '`covid`.`fecha`',
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
		7 => '`covid`.`nacimiento`',
		8 => '`covid`.`edad`',
		9 => 9,
		10 => '`regimenes1`.`nombre`',
		11 => '`eps1`.`razonsocial`',
		12 => 12,
		13 => 13,
		14 => 14,
		15 => 15,
		16 => 16,
		17 => 17,
		18 => 18,
		19 => 19,
		20 => 20,
		21 => 21,
		22 => 22,
		23 => 23,
		24 => 24,
		25 => 25,
		26 => 26,
		27 => 27,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`covid`.`id`" => "id",
		"if(`covid`.`fecha`,date_format(`covid`.`fecha`,'%d/%m/%Y'),'')" => "fecha",
		"`covid`.`tipodoc`" => "tipodoc",
		"`covid`.`doc`" => "doc",
		"`covid`.`nombre`" => "nombre",
		"`covid`.`genero`" => "genero",
		"if(`covid`.`nacimiento`,date_format(`covid`.`nacimiento`,'%d/%m/%Y'),'')" => "nacimiento",
		"`covid`.`edad`" => "edad",
		"`covid`.`telefono`" => "telefono",
		"IF(    CHAR_LENGTH(`regimenes1`.`nombre`), CONCAT_WS('',   `regimenes1`.`nombre`), '') /* Regimen */" => "regimen",
		"IF(    CHAR_LENGTH(`eps1`.`razonsocial`), CONCAT_WS('',   `eps1`.`razonsocial`), '') /* EPS */" => "eps",
		"`covid`.`embarazo`" => "embarazo",
		"`covid`.`patologia`" => "patologia",
		"`covid`.`fallecido`" => "fallecido",
		"IF(    CHAR_LENGTH(`cie101`.`cie10`) || CHAR_LENGTH(`cie101`.`descripcion`), CONCAT_WS('',   `cie101`.`cie10`, ' - ', `cie101`.`descripcion`), '') /* Cual? */" => "cual",
		"`covid`.`atencion`" => "atencion",
		"`covid`.`tratamiento`" => "tratamiento",
		"`covid`.`medicamentos`" => "medicamentos",
		"`covid`.`vigilancia`" => "vigilancia",
		"`covid`.`percepcion`" => "percepcion",
		"`covid`.`medicinageneral`" => "medicinageneral",
		"`covid`.`oportunidad`" => "oportunidad",
		"`covid`.`observacion`" => "observacion",
		"`covid`.`status`" => "status",
		"`covid`.`responsable`" => "responsable",
		"`covid`.`periodo`" => "periodo",
		"`covid`.`asignado`" => "asignado",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`covid`.`id`" => "ID",
		"`covid`.`fecha`" => "Fecha",
		"`covid`.`tipodoc`" => "Tipo de Documento",
		"`covid`.`doc`" => "Documento",
		"`covid`.`nombre`" => "Nombre Completo",
		"`covid`.`genero`" => "Genero",
		"`covid`.`nacimiento`" => "Fecha de Nacimiento",
		"`covid`.`edad`" => "Edad",
		"`covid`.`telefono`" => "Telefono",
		"IF(    CHAR_LENGTH(`regimenes1`.`nombre`), CONCAT_WS('',   `regimenes1`.`nombre`), '') /* Regimen */" => "Regimen",
		"IF(    CHAR_LENGTH(`eps1`.`razonsocial`), CONCAT_WS('',   `eps1`.`razonsocial`), '') /* EPS */" => "EPS",
		"`covid`.`embarazo`" => "Se encuentra ud en embarazo?",
		"`covid`.`patologia`" => "Tiene alguna patolog&#237;a?",
		"`covid`.`fallecido`" => "Fallecido",
		"IF(    CHAR_LENGTH(`cie101`.`cie10`) || CHAR_LENGTH(`cie101`.`descripcion`), CONCAT_WS('',   `cie101`.`cie10`, ' - ', `cie101`.`descripcion`), '') /* Cual? */" => "Cual?",
		"`covid`.`atencion`" => "LA EPS HA ATENDIDO SUS NECESIDADES DURANTE EL ESTADO DE EMERGENCIA? DE QUE FORMA?",
		"`covid`.`tratamiento`" => "Le han ordenado tratamiento medico durante el periodo de Emergencia?",
		"`covid`.`medicamentos`" => "LE HAN HECHO ENTREGA DE MEDICAMENTOS EN SU DOMICILIO DURANTE LA EMERGENCIA?",
		"`covid`.`vigilancia`" => "La he EPS ha hecho seguimiento sobre su condici&#243;n de salud?",
		"`covid`.`percepcion`" => "Cual es su nivel de satisfacci&#243;n con su EPS?",
		"`covid`.`medicinageneral`" => "Recientemente ha solicitado citas de Medicina General?",
		"`covid`.`oportunidad`" => "A cuantos d&#237;as le fue dada la ultima cita solicitada?",
		"`covid`.`observacion`" => "Observacion",
		"`covid`.`status`" => "Estado",
		"`covid`.`responsable`" => "Responsable",
		"`covid`.`periodo`" => "Periodo",
		"`covid`.`asignado`" => "Asignado a",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`covid`.`id`" => "id",
		"if(`covid`.`fecha`,date_format(`covid`.`fecha`,'%d/%m/%Y'),'')" => "fecha",
		"`covid`.`tipodoc`" => "tipodoc",
		"`covid`.`doc`" => "doc",
		"`covid`.`nombre`" => "nombre",
		"`covid`.`genero`" => "genero",
		"if(`covid`.`nacimiento`,date_format(`covid`.`nacimiento`,'%d/%m/%Y'),'')" => "nacimiento",
		"`covid`.`edad`" => "edad",
		"`covid`.`telefono`" => "telefono",
		"IF(    CHAR_LENGTH(`regimenes1`.`nombre`), CONCAT_WS('',   `regimenes1`.`nombre`), '') /* Regimen */" => "regimen",
		"IF(    CHAR_LENGTH(`eps1`.`razonsocial`), CONCAT_WS('',   `eps1`.`razonsocial`), '') /* EPS */" => "eps",
		"`covid`.`embarazo`" => "embarazo",
		"concat('<i class=\"glyphicon glyphicon-', if(`covid`.`patologia`, 'check', 'unchecked'), '\"></i>')" => "patologia",
		"concat('<i class=\"glyphicon glyphicon-', if(`covid`.`fallecido`, 'check', 'unchecked'), '\"></i>')" => "fallecido",
		"IF(    CHAR_LENGTH(`cie101`.`cie10`) || CHAR_LENGTH(`cie101`.`descripcion`), CONCAT_WS('',   `cie101`.`cie10`, ' - ', `cie101`.`descripcion`), '') /* Cual? */" => "cual",
		"`covid`.`atencion`" => "atencion",
		"`covid`.`tratamiento`" => "tratamiento",
		"`covid`.`medicamentos`" => "medicamentos",
		"`covid`.`vigilancia`" => "vigilancia",
		"`covid`.`percepcion`" => "percepcion",
		"concat('<i class=\"glyphicon glyphicon-', if(`covid`.`medicinageneral`, 'check', 'unchecked'), '\"></i>')" => "medicinageneral",
		"`covid`.`oportunidad`" => "oportunidad",
		"`covid`.`observacion`" => "observacion",
		"`covid`.`status`" => "status",
		"`covid`.`responsable`" => "responsable",
		"`covid`.`periodo`" => "periodo",
		"`covid`.`asignado`" => "asignado",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['regimen' => 'Regimen', 'eps' => 'EPS', 'cual' => 'Cual?', ];

	$x->QueryFrom = "`covid` LEFT JOIN `regimenes` as regimenes1 ON `regimenes1`.`nombre`=`covid`.`regimen` LEFT JOIN `eps` as eps1 ON `eps1`.`razonsocial`=`covid`.`eps` LEFT JOIN `cie10` as cie101 ON `cie101`.`cie10`=`covid`.`cual` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = (getLoggedAdmin() !== false);
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = (getLoggedAdmin() !== false);
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 50;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'covid_view.php';
	$x->RedirectAfterInsert = 'covid_view.php?SelectedID=#ID#';
	$x->TableTitle = 'Encuesta 521';
	$x->TableIcon = 'resources/table_icons/health.png';
	$x->PrimaryKey = '`covid`.`id`';
	$x->DefaultSortField = '24';
	$x->DefaultSortDirection = 'asc';

	$x->ColWidth = [150, 150, 150, 150, 400, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['ID', 'Fecha', 'Tipo de Documento', 'Documento', 'Nombre Completo', 'Genero', 'Fecha de Nacimiento', 'Telefono', 'EPS', 'Fallecido', 'LA EPS HA ATENDIDO SUS NECESIDADES DURANTE EL ESTADO DE EMERGENCIA? DE QUE FORMA?', 'LE HAN HECHO ENTREGA DE MEDICAMENTOS EN SU DOMICILIO DURANTE LA EMERGENCIA?', 'Recientemente ha solicitado citas de Medicina General?', 'A cuantos d&#237;as le fue dada la ultima cita solicitada?', 'Estado', 'Asignado a', ];
	$x->ColFieldName = ['id', 'fecha', 'tipodoc', 'doc', 'nombre', 'genero', 'nacimiento', 'telefono', 'eps', 'fallecido', 'atencion', 'medicamentos', 'medicinageneral', 'oportunidad', 'status', 'asignado', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, 6, 7, 9, 11, 14, 16, 18, 21, 22, 24, 27, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/covid_templateTV.html';
	$x->SelectedTemplate = 'templates/covid_templateTVS.html';
	$x->TemplateDV = 'templates/covid_templateDV.html';
	$x->TemplateDVP = 'templates/covid_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = true;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: covid_init
	$render = true;
	if(function_exists('covid_init')) {
		$args = [];
		$render = covid_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: covid_header
	$headerCode = '';
	if(function_exists('covid_header')) {
		$args = [];
		$headerCode = covid_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once("{$currDir}/header.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/header.php");
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: covid_footer
	$footerCode = '';
	if(function_exists('covid_footer')) {
		$args = [];
		$footerCode = covid_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once("{$currDir}/footer.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/footer.php");
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
