<?php

// Data functions (insert, update, delete, form) for table covid

// This script and data application were generated by AppGini 5.97
// Download AppGini for free from https://bigprof.com/appgini/download/

function covid_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('covid');
	if(!$arrPerm['insert']) return false;

	$data = [
		'tipodoc' => Request::val('tipodoc', ''),
		'doc' => Request::val('doc', ''),
		'nombre' => Request::val('nombre', ''),
		'genero' => Request::val('genero', ''),
		'nacimiento' => Request::dateComponents('nacimiento', ''),
		'edad' => Request::val('edad', 'Edad'),
		'telefono' => Request::val('telefono', ''),
		'regimen' => Request::lookup('regimen', ''),
		'eps' => Request::lookup('eps', ''),
		'embarazo' => Request::val('embarazo', ''),
		'patologia' => Request::checkBox('patologia', '0'),
		'fallecido' => Request::checkBox('fallecido', ''),
		'cual' => Request::lookup('cual', ''),
		'atencion' => Request::multipleChoice('atencion', ''),
		'tratamiento' => Request::val('tratamiento', ''),
		'medicamentos' => Request::val('medicamentos', ''),
		'vigilancia' => Request::val('vigilancia', ''),
		'percepcion' => Request::val('percepcion', ''),
		'medicinageneral' => Request::checkBox('medicinageneral', ''),
		'oportunidad' => Request::val('oportunidad', ''),
		'observacion' => br2nl(Request::val('observacion', 'SIN OBSERVACION')),
		'status' => Request::val('status', ''),
	];

	if($data['tipodoc'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Tipo de Documento': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['doc'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Documento': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['nombre'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Nombre Completo': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['genero'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Genero': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['nacimiento'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Fecha de Nacimiento': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['edad'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Edad': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['telefono'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Telefono': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['eps'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'EPS': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['embarazo'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Se encuentra ud en embarazo?': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['atencion'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'LA EPS HA ATENDIDO SUS NECESIDADES DURANTE EL ESTADO DE EMERGENCIA? DE QUE FORMA?': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['tratamiento'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Le han ordenado tratamiento medico durante el periodo de Emergencia?': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['medicamentos'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'LE HAN HECHO ENTREGA DE MEDICAMENTOS EN SU DOMICILIO DURANTE LA EMERGENCIA?': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['vigilancia'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'La he EPS ha hecho seguimiento sobre su condici&#243;n de salud?': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['percepcion'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Cual es su nivel de satisfacci&#243;n con su EPS?': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['status'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Estado': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}

	// hook: covid_before_insert
	if(function_exists('covid_before_insert')) {
		$args = [];
		if(!covid_before_insert($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('covid', backtick_keys_once($data), $error);
	if($error)
		die("{$error}<br><a href=\"#\" onclick=\"history.go(-1);\">{$Translation['< back']}</a>");

	$recID = db_insert_id(db_link());

	update_calc_fields('covid', $recID, calculated_fields()['covid']);

	// hook: covid_after_insert
	if(function_exists('covid_after_insert')) {
		$res = sql("SELECT * FROM `covid` WHERE `id`='" . makeSafe($recID, false) . "' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=[];
		if(!covid_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	set_record_owner('covid', $recID, getLoggedMemberID());

	// if this record is a copy of another record, copy children if applicable
	if(!empty($_REQUEST['SelectedID'])) covid_copy_children($recID, $_REQUEST['SelectedID']);

	return $recID;
}

function covid_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function covid_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('covid', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: covid_before_delete
	if(function_exists('covid_before_delete')) {
		$args = [];
		if(!covid_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: '' 
			);
	}

	sql("DELETE FROM `covid` WHERE `id`='{$selected_id}'", $eo);

	// hook: covid_after_delete
	if(function_exists('covid_after_delete')) {
		$args = [];
		covid_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='covid' AND `pkValue`='{$selected_id}'", $eo);
}

function covid_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('covid', $selected_id, 'edit')) return false;

	$data = [
		'fecha' => parseCode('<%%editingDateTime%%>', false, true),
		'tipodoc' => Request::val('tipodoc', ''),
		'doc' => Request::val('doc', ''),
		'nombre' => Request::val('nombre', ''),
		'genero' => Request::val('genero', ''),
		'nacimiento' => Request::dateComponents('nacimiento', ''),
		'edad' => Request::val('edad', ''),
		'telefono' => Request::val('telefono', ''),
		'regimen' => Request::lookup('regimen', ''),
		'eps' => Request::lookup('eps', ''),
		'embarazo' => Request::val('embarazo', ''),
		'patologia' => Request::checkBox('patologia', ''),
		'fallecido' => Request::checkBox('fallecido', ''),
		'cual' => Request::lookup('cual', ''),
		'atencion' => Request::multipleChoice('atencion', ''),
		'tratamiento' => Request::val('tratamiento', ''),
		'medicamentos' => Request::val('medicamentos', ''),
		'vigilancia' => Request::val('vigilancia', ''),
		'percepcion' => Request::val('percepcion', ''),
		'medicinageneral' => Request::checkBox('medicinageneral', ''),
		'oportunidad' => Request::val('oportunidad', ''),
		'observacion' => br2nl(Request::val('observacion', '')),
		'status' => Request::val('status', ''),
		'responsable' => parseCode('<%%editorUsername%%>', false),
	];

	if($data['tipodoc'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Tipo de Documento': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['doc'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Documento': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['nombre'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Nombre Completo': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['genero'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Genero': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['nacimiento'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Fecha de Nacimiento': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['edad'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Edad': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['telefono'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Telefono': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['eps'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'EPS': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['embarazo'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Se encuentra ud en embarazo?': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['atencion'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'LA EPS HA ATENDIDO SUS NECESIDADES DURANTE EL ESTADO DE EMERGENCIA? DE QUE FORMA?': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['tratamiento'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Le han ordenado tratamiento medico durante el periodo de Emergencia?': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['medicamentos'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'LE HAN HECHO ENTREGA DE MEDICAMENTOS EN SU DOMICILIO DURANTE LA EMERGENCIA?': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['vigilancia'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'La he EPS ha hecho seguimiento sobre su condici&#243;n de salud?': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['percepcion'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Cual es su nivel de satisfacci&#243;n con su EPS?': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['status'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Estado': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	// get existing values
	$old_data = getRecord('covid', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: covid_before_update
	if(function_exists('covid_before_update')) {
		$args = ['old_data' => $old_data];
		if(!covid_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'covid', 
		backtick_keys_once($set), 
		['`id`' => $selected_id], 
		$error_message
	)) {
		echo $error_message;
		echo '<a href="covid_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	$eo = ['silentErrors' => true];

	update_calc_fields('covid', $data['selectedID'], calculated_fields()['covid']);

	// hook: covid_after_update
	if(function_exists('covid_after_update')) {
		$res = sql("SELECT * FROM `covid` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['id'];
		$args = ['old_data' => $old_data];
		if(!covid_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update ownership data
	sql("UPDATE `membership_userrecords` SET `dateUpdated`='" . time() . "' WHERE `tableName`='covid' AND `pkValue`='" . makeSafe($selected_id) . "'", $eo);
}

function covid_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0, $TemplateDV = '', $TemplateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm = getTablePermissions('covid');
	if(!$arrPerm['insert'] && $selected_id=='') return $Translation['tableAccessDenied'];
	$AllowInsert = ($arrPerm['insert'] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != '') {
		$dvprint = true;
	}

	$filterer_regimen = thisOr($_REQUEST['filterer_regimen'], '');
	$filterer_eps = thisOr($_REQUEST['filterer_eps'], '');
	$filterer_cual = thisOr($_REQUEST['filterer_cual'], '');

	// populate filterers, starting from children to grand-parents
	if($filterer_eps && !$filterer_regimen) $filterer_regimen = sqlValue("select regimen from eps where razonsocial='" . makeSafe($filterer_eps) . "'");

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: fecha
	$combo_fecha = new DateCombo;
	$combo_fecha->DateFormat = "dmy";
	$combo_fecha->MinYear = 1900;
	$combo_fecha->MaxYear = 2100;
	$combo_fecha->DefaultDate = parseMySQLDate('<%%editingDateTime%%>', '<%%editingDateTime%%>');
	$combo_fecha->MonthNames = $Translation['month names'];
	$combo_fecha->NamePrefix = 'fecha';
	// combobox: tipodoc
	$combo_tipodoc = new Combo;
	$combo_tipodoc->ListType = 0;
	$combo_tipodoc->MultipleSeparator = ', ';
	$combo_tipodoc->ListBoxHeight = 10;
	$combo_tipodoc->RadiosPerLine = 1;
	if(is_file(dirname(__FILE__).'/hooks/covid.tipodoc.csv')) {
		$tipodoc_data = addslashes(implode('', @file(dirname(__FILE__).'/hooks/covid.tipodoc.csv')));
		$combo_tipodoc->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions($tipodoc_data)));
		$combo_tipodoc->ListData = $combo_tipodoc->ListItem;
	} else {
		$combo_tipodoc->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions(";;RC;;TI;;CC;;CE;;PAS;;PEP;;OTRO")));
		$combo_tipodoc->ListData = $combo_tipodoc->ListItem;
	}
	$combo_tipodoc->SelectName = 'tipodoc';
	$combo_tipodoc->AllowNull = false;
	// combobox: genero
	$combo_genero = new Combo;
	$combo_genero->ListType = 0;
	$combo_genero->MultipleSeparator = ', ';
	$combo_genero->ListBoxHeight = 10;
	$combo_genero->RadiosPerLine = 1;
	if(is_file(dirname(__FILE__).'/hooks/covid.genero.csv')) {
		$genero_data = addslashes(implode('', @file(dirname(__FILE__).'/hooks/covid.genero.csv')));
		$combo_genero->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions($genero_data)));
		$combo_genero->ListData = $combo_genero->ListItem;
	} else {
		$combo_genero->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions(";;F;;M;;N/A")));
		$combo_genero->ListData = $combo_genero->ListItem;
	}
	$combo_genero->SelectName = 'genero';
	$combo_genero->AllowNull = false;
	// combobox: nacimiento
	$combo_nacimiento = new DateCombo;
	$combo_nacimiento->DateFormat = "dmy";
	$combo_nacimiento->MinYear = 1900;
	$combo_nacimiento->MaxYear = 2100;
	$combo_nacimiento->DefaultDate = parseMySQLDate('', '');
	$combo_nacimiento->MonthNames = $Translation['month names'];
	$combo_nacimiento->NamePrefix = 'nacimiento';
	// combobox: regimen
	$combo_regimen = new DataCombo;
	// combobox: eps, filterable by: regimen
	$combo_eps = new DataCombo;
	// combobox: embarazo
	$combo_embarazo = new Combo;
	$combo_embarazo->ListType = 0;
	$combo_embarazo->MultipleSeparator = ', ';
	$combo_embarazo->ListBoxHeight = 10;
	$combo_embarazo->RadiosPerLine = 1;
	if(is_file(dirname(__FILE__).'/hooks/covid.embarazo.csv')) {
		$embarazo_data = addslashes(implode('', @file(dirname(__FILE__).'/hooks/covid.embarazo.csv')));
		$combo_embarazo->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions($embarazo_data)));
		$combo_embarazo->ListData = $combo_embarazo->ListItem;
	} else {
		$combo_embarazo->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions(";;SI;;NO;;NO APLICA")));
		$combo_embarazo->ListData = $combo_embarazo->ListItem;
	}
	$combo_embarazo->SelectName = 'embarazo';
	$combo_embarazo->AllowNull = false;
	// combobox: cual
	$combo_cual = new DataCombo;
	// combobox: atencion
	$combo_atencion = new Combo;
	$combo_atencion->ListType = 3;
	$combo_atencion->MultipleSeparator = ', ';
	$combo_atencion->ListBoxHeight = 10;
	$combo_atencion->RadiosPerLine = 1;
	if(is_file(dirname(__FILE__).'/hooks/covid.atencion.csv')) {
		$atencion_data = addslashes(implode('', @file(dirname(__FILE__).'/hooks/covid.atencion.csv')));
		$combo_atencion->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions($atencion_data)));
		$combo_atencion->ListData = $combo_atencion->ListItem;
	} else {
		$combo_atencion->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions("VIRTUAL;;TELEFONICA;;PRESENCIAL-CASA;;PRESENCIAL-CLINICA;;NO HA RECIBIDO ATENCION")));
		$combo_atencion->ListData = $combo_atencion->ListItem;
	}
	$combo_atencion->SelectName = 'atencion';
	$combo_atencion->AllowNull = false;
	// combobox: tratamiento
	$combo_tratamiento = new Combo;
	$combo_tratamiento->ListType = 0;
	$combo_tratamiento->MultipleSeparator = ', ';
	$combo_tratamiento->ListBoxHeight = 10;
	$combo_tratamiento->RadiosPerLine = 1;
	if(is_file(dirname(__FILE__).'/hooks/covid.tratamiento.csv')) {
		$tratamiento_data = addslashes(implode('', @file(dirname(__FILE__).'/hooks/covid.tratamiento.csv')));
		$combo_tratamiento->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions($tratamiento_data)));
		$combo_tratamiento->ListData = $combo_tratamiento->ListItem;
	} else {
		$combo_tratamiento->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions(";;SI;;NO")));
		$combo_tratamiento->ListData = $combo_tratamiento->ListItem;
	}
	$combo_tratamiento->SelectName = 'tratamiento';
	$combo_tratamiento->AllowNull = false;
	// combobox: medicamentos
	$combo_medicamentos = new Combo;
	$combo_medicamentos->ListType = 0;
	$combo_medicamentos->MultipleSeparator = ', ';
	$combo_medicamentos->ListBoxHeight = 10;
	$combo_medicamentos->RadiosPerLine = 1;
	if(is_file(dirname(__FILE__).'/hooks/covid.medicamentos.csv')) {
		$medicamentos_data = addslashes(implode('', @file(dirname(__FILE__).'/hooks/covid.medicamentos.csv')));
		$combo_medicamentos->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions($medicamentos_data)));
		$combo_medicamentos->ListData = $combo_medicamentos->ListItem;
	} else {
		$combo_medicamentos->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions(";;SI;;NO")));
		$combo_medicamentos->ListData = $combo_medicamentos->ListItem;
	}
	$combo_medicamentos->SelectName = 'medicamentos';
	$combo_medicamentos->AllowNull = false;
	// combobox: vigilancia
	$combo_vigilancia = new Combo;
	$combo_vigilancia->ListType = 0;
	$combo_vigilancia->MultipleSeparator = ', ';
	$combo_vigilancia->ListBoxHeight = 10;
	$combo_vigilancia->RadiosPerLine = 1;
	if(is_file(dirname(__FILE__).'/hooks/covid.vigilancia.csv')) {
		$vigilancia_data = addslashes(implode('', @file(dirname(__FILE__).'/hooks/covid.vigilancia.csv')));
		$combo_vigilancia->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions($vigilancia_data)));
		$combo_vigilancia->ListData = $combo_vigilancia->ListItem;
	} else {
		$combo_vigilancia->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions(";;SI;;NO")));
		$combo_vigilancia->ListData = $combo_vigilancia->ListItem;
	}
	$combo_vigilancia->SelectName = 'vigilancia';
	$combo_vigilancia->AllowNull = false;
	// combobox: percepcion
	$combo_percepcion = new Combo;
	$combo_percepcion->ListType = 0;
	$combo_percepcion->MultipleSeparator = ', ';
	$combo_percepcion->ListBoxHeight = 10;
	$combo_percepcion->RadiosPerLine = 1;
	if(is_file(dirname(__FILE__).'/hooks/covid.percepcion.csv')) {
		$percepcion_data = addslashes(implode('', @file(dirname(__FILE__).'/hooks/covid.percepcion.csv')));
		$combo_percepcion->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions($percepcion_data)));
		$combo_percepcion->ListData = $combo_percepcion->ListItem;
	} else {
		$combo_percepcion->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions(";;EXCELENTE;;BUENA;;REGULAR;;MALA")));
		$combo_percepcion->ListData = $combo_percepcion->ListItem;
	}
	$combo_percepcion->SelectName = 'percepcion';
	$combo_percepcion->AllowNull = false;
	// combobox: oportunidad
	$combo_oportunidad = new Combo;
	$combo_oportunidad->ListType = 0;
	$combo_oportunidad->MultipleSeparator = ', ';
	$combo_oportunidad->ListBoxHeight = 10;
	$combo_oportunidad->RadiosPerLine = 1;
	if(is_file(dirname(__FILE__).'/hooks/covid.oportunidad.csv')) {
		$oportunidad_data = addslashes(implode('', @file(dirname(__FILE__).'/hooks/covid.oportunidad.csv')));
		$combo_oportunidad->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions($oportunidad_data)));
		$combo_oportunidad->ListData = $combo_oportunidad->ListItem;
	} else {
		$combo_oportunidad->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions(";;1;;2;;3;;4;;5;;6;;7;;8;;9;;10;;11;;12;;13;;14;;15;;16;;17;;18;;19;;20;;21;;MAS DE 21 DIAS")));
		$combo_oportunidad->ListData = $combo_oportunidad->ListItem;
	}
	$combo_oportunidad->SelectName = 'oportunidad';
	// combobox: status
	$combo_status = new Combo;
	$combo_status->ListType = 0;
	$combo_status->MultipleSeparator = ', ';
	$combo_status->ListBoxHeight = 10;
	$combo_status->RadiosPerLine = 1;
	if(is_file(dirname(__FILE__).'/hooks/covid.status.csv')) {
		$status_data = addslashes(implode('', @file(dirname(__FILE__).'/hooks/covid.status.csv')));
		$combo_status->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions($status_data)));
		$combo_status->ListData = $combo_status->ListItem;
	} else {
		$combo_status->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions("Encuestado;;")));
		$combo_status->ListData = $combo_status->ListItem;
	}
	$combo_status->SelectName = 'status';
	$combo_status->AllowNull = false;

	if($selected_id) {
		// mm: check member permissions
		if(!$arrPerm['view']) return $Translation['tableAccessDenied'];

		// mm: who is the owner?
		$ownerGroupID = sqlValue("SELECT `groupID` FROM `membership_userrecords` WHERE `tableName`='covid' AND `pkValue`='" . makeSafe($selected_id) . "'");
		$ownerMemberID = sqlValue("SELECT LCASE(`memberID`) FROM `membership_userrecords` WHERE `tableName`='covid' AND `pkValue`='" . makeSafe($selected_id) . "'");

		if($arrPerm['view'] == 1 && getLoggedMemberID() != $ownerMemberID) return $Translation['tableAccessDenied'];
		if($arrPerm['view'] == 2 && getLoggedGroupID() != $ownerGroupID) return $Translation['tableAccessDenied'];

		// can edit?
		$AllowUpdate = 0;
		if(($arrPerm['edit'] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm['edit'] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm['edit'] == 3) {
			$AllowUpdate = 1;
		}

		$res = sql("SELECT * FROM `covid` WHERE `id`='" . makeSafe($selected_id) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'covid_view.php', false);
		}
		$combo_fecha->DefaultDate = $row['fecha'];
		$combo_tipodoc->SelectedData = $row['tipodoc'];
		$combo_genero->SelectedData = $row['genero'];
		$combo_nacimiento->DefaultDate = $row['nacimiento'];
		$combo_regimen->SelectedData = $row['regimen'];
		$combo_eps->SelectedData = $row['eps'];
		$combo_embarazo->SelectedData = $row['embarazo'];
		$combo_cual->SelectedData = $row['cual'];
		$combo_atencion->SelectedData = $row['atencion'];
		$combo_tratamiento->SelectedData = $row['tratamiento'];
		$combo_medicamentos->SelectedData = $row['medicamentos'];
		$combo_vigilancia->SelectedData = $row['vigilancia'];
		$combo_percepcion->SelectedData = $row['percepcion'];
		$combo_oportunidad->SelectedData = $row['oportunidad'];
		$combo_status->SelectedData = $row['status'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$combo_tipodoc->SelectedText = ( $_REQUEST['FilterField'][1] == '3' && $_REQUEST['FilterOperator'][1] == '<=>' ? $_REQUEST['FilterValue'][1] : '');
		$combo_genero->SelectedText = ( $_REQUEST['FilterField'][1] == '6' && $_REQUEST['FilterOperator'][1] == '<=>' ? $_REQUEST['FilterValue'][1] : '');
		$combo_regimen->SelectedData = $filterer_regimen;
		$combo_eps->SelectedData = $filterer_eps;
		$combo_embarazo->SelectedText = ( $_REQUEST['FilterField'][1] == '12' && $_REQUEST['FilterOperator'][1] == '<=>' ? $_REQUEST['FilterValue'][1] : '');
		$combo_cual->SelectedData = $filterer_cual;
		$combo_tratamiento->SelectedText = ( $_REQUEST['FilterField'][1] == '17' && $_REQUEST['FilterOperator'][1] == '<=>' ? $_REQUEST['FilterValue'][1] : '');
		$combo_medicamentos->SelectedText = ( $_REQUEST['FilterField'][1] == '18' && $_REQUEST['FilterOperator'][1] == '<=>' ? $_REQUEST['FilterValue'][1] : '');
		$combo_vigilancia->SelectedText = ( $_REQUEST['FilterField'][1] == '19' && $_REQUEST['FilterOperator'][1] == '<=>' ? $_REQUEST['FilterValue'][1] : '');
		$combo_percepcion->SelectedText = ( $_REQUEST['FilterField'][1] == '20' && $_REQUEST['FilterOperator'][1] == '<=>' ? $_REQUEST['FilterValue'][1] : '');
		$combo_oportunidad->SelectedText = ( $_REQUEST['FilterField'][1] == '22' && $_REQUEST['FilterOperator'][1] == '<=>' ? $_REQUEST['FilterValue'][1] : '');
		$combo_status->SelectedText = ( $_REQUEST['FilterField'][1] == '24' && $_REQUEST['FilterOperator'][1] == '<=>' ? $_REQUEST['FilterValue'][1] : '');
	}
	$combo_tipodoc->Render();
	$combo_genero->Render();
	$combo_regimen->HTML = '<span id="regimen-container' . $rnd1 . '"></span><input type="hidden" name="regimen" id="regimen' . $rnd1 . '" value="' . html_attr($combo_regimen->SelectedData) . '">';
	$combo_regimen->MatchText = '<span id="regimen-container-readonly' . $rnd1 . '"></span><input type="hidden" name="regimen" id="regimen' . $rnd1 . '" value="' . html_attr($combo_regimen->SelectedData) . '">';
	$combo_eps->HTML = '<span id="eps-container' . $rnd1 . '"></span><input type="hidden" name="eps" id="eps' . $rnd1 . '" value="' . html_attr($combo_eps->SelectedData) . '">';
	$combo_eps->MatchText = '<span id="eps-container-readonly' . $rnd1 . '"></span><input type="hidden" name="eps" id="eps' . $rnd1 . '" value="' . html_attr($combo_eps->SelectedData) . '">';
	$combo_embarazo->Render();
	$combo_cual->HTML = '<span id="cual-container' . $rnd1 . '"></span><input type="hidden" name="cual" id="cual' . $rnd1 . '" value="' . html_attr($combo_cual->SelectedData) . '">';
	$combo_cual->MatchText = '<span id="cual-container-readonly' . $rnd1 . '"></span><input type="hidden" name="cual" id="cual' . $rnd1 . '" value="' . html_attr($combo_cual->SelectedData) . '">';
	$combo_atencion->Render();
	$combo_tratamiento->Render();
	$combo_medicamentos->Render();
	$combo_vigilancia->Render();
	$combo_percepcion->Render();
	$combo_oportunidad->Render();
	$combo_status->Render();

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_regimen__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['regimen'] : htmlspecialchars($filterer_regimen, ENT_QUOTES)); ?>"};
		AppGini.current_eps__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['eps'] : htmlspecialchars($filterer_eps, ENT_QUOTES)); ?>"};
		AppGini.current_cual__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['cual'] : htmlspecialchars($filterer_cual, ENT_QUOTES)); ?>"};

		jQuery(function() {
			setTimeout(function() {
				if(typeof(regimen_reload__RAND__) == 'function') regimen_reload__RAND__();
				<?php echo (!$AllowUpdate || $dvprint ? 'if(typeof(eps_reload__RAND__) == \'function\') eps_reload__RAND__(AppGini.current_regimen__RAND__.value);' : ''); ?>
				if(typeof(cual_reload__RAND__) == 'function') cual_reload__RAND__();
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function regimen_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#regimen-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_regimen__RAND__.value, t: 'covid', f: 'regimen' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="regimen"]').val(resp.results[0].id);
							$j('[id=regimen-container-readonly__RAND__]').html('<span id="regimen-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=regimenes_view_parent]').hide(); } else { $j('.btn[id=regimenes_view_parent]').show(); }

						if(typeof(eps_reload__RAND__) == 'function') eps_reload__RAND__(AppGini.current_regimen__RAND__.value);

							if(typeof(regimen_update_autofills__RAND__) == 'function') regimen_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'covid', f: 'regimen' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_regimen__RAND__.value = e.added.id;
				AppGini.current_regimen__RAND__.text = e.added.text;
				$j('[name="regimen"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=regimenes_view_parent]').hide(); } else { $j('.btn[id=regimenes_view_parent]').show(); }

						if(typeof(eps_reload__RAND__) == 'function') eps_reload__RAND__(AppGini.current_regimen__RAND__.value);

				if(typeof(regimen_update_autofills__RAND__) == 'function') regimen_update_autofills__RAND__();
			});

			if(!$j("#regimen-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_regimen__RAND__.value, t: 'covid', f: 'regimen' },
					success: function(resp) {
						$j('[name="regimen"]').val(resp.results[0].id);
						$j('[id=regimen-container-readonly__RAND__]').html('<span id="regimen-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=regimenes_view_parent]').hide(); } else { $j('.btn[id=regimenes_view_parent]').show(); }

						if(typeof(regimen_update_autofills__RAND__) == 'function') regimen_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_regimen__RAND__.value, t: 'covid', f: 'regimen' },
				success: function(resp) {
					$j('[id=regimen-container__RAND__], [id=regimen-container-readonly__RAND__]').html('<span id="regimen-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=regimenes_view_parent]').hide(); } else { $j('.btn[id=regimenes_view_parent]').show(); }

					if(typeof(regimen_update_autofills__RAND__) == 'function') regimen_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function eps_reload__RAND__(filterer_regimen) {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#eps-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { filterer_regimen: filterer_regimen, id: AppGini.current_eps__RAND__.value, t: 'covid', f: 'eps' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="eps"]').val(resp.results[0].id);
							$j('[id=eps-container-readonly__RAND__]').html('<span id="eps-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=eps_view_parent]').hide(); } else { $j('.btn[id=eps_view_parent]').show(); }


							if(typeof(eps_update_autofills__RAND__) == 'function') eps_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { filterer_regimen: filterer_regimen, s: term, p: page, t: 'covid', f: 'eps' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_eps__RAND__.value = e.added.id;
				AppGini.current_eps__RAND__.text = e.added.text;
				$j('[name="eps"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=eps_view_parent]').hide(); } else { $j('.btn[id=eps_view_parent]').show(); }


				if(typeof(eps_update_autofills__RAND__) == 'function') eps_update_autofills__RAND__();
			});

			if(!$j("#eps-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_eps__RAND__.value, t: 'covid', f: 'eps' },
					success: function(resp) {
						$j('[name="eps"]').val(resp.results[0].id);
						$j('[id=eps-container-readonly__RAND__]').html('<span id="eps-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=eps_view_parent]').hide(); } else { $j('.btn[id=eps_view_parent]').show(); }

						if(typeof(eps_update_autofills__RAND__) == 'function') eps_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_eps__RAND__.value, t: 'covid', f: 'eps' },
				success: function(resp) {
					$j('[id=eps-container__RAND__], [id=eps-container-readonly__RAND__]').html('<span id="eps-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=eps_view_parent]').hide(); } else { $j('.btn[id=eps_view_parent]').show(); }

					if(typeof(eps_update_autofills__RAND__) == 'function') eps_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function cual_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#cual-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_cual__RAND__.value, t: 'covid', f: 'cual' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="cual"]').val(resp.results[0].id);
							$j('[id=cual-container-readonly__RAND__]').html('<span id="cual-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=cie10_view_parent]').hide(); } else { $j('.btn[id=cie10_view_parent]').show(); }


							if(typeof(cual_update_autofills__RAND__) == 'function') cual_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'covid', f: 'cual' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_cual__RAND__.value = e.added.id;
				AppGini.current_cual__RAND__.text = e.added.text;
				$j('[name="cual"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=cie10_view_parent]').hide(); } else { $j('.btn[id=cie10_view_parent]').show(); }


				if(typeof(cual_update_autofills__RAND__) == 'function') cual_update_autofills__RAND__();
			});

			if(!$j("#cual-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_cual__RAND__.value, t: 'covid', f: 'cual' },
					success: function(resp) {
						$j('[name="cual"]').val(resp.results[0].id);
						$j('[id=cual-container-readonly__RAND__]').html('<span id="cual-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=cie10_view_parent]').hide(); } else { $j('.btn[id=cie10_view_parent]').show(); }

						if(typeof(cual_update_autofills__RAND__) == 'function') cual_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_cual__RAND__.value, t: 'covid', f: 'cual' },
				success: function(resp) {
					$j('[id=cual-container__RAND__], [id=cual-container-readonly__RAND__]').html('<span id="cual-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=cie10_view_parent]').hide(); } else { $j('.btn[id=cie10_view_parent]').show(); }

					if(typeof(cual_update_autofills__RAND__) == 'function') cual_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/covid_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/covid_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Detalle de Encuesta', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($arrPerm[1] && !$selected_id) { // allow insert and no record selected?
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return covid_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return covid_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id) {
		if(!$_REQUEST['Embedded']) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate) {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return covid_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		} else {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3) { // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		} else {
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate) || (!$selected_id && !$AllowInsert)) {
		$jsReadOnly = '';
		$jsReadOnly .= "\tjQuery('#tipodoc').replaceWith('<div class=\"form-control-static\" id=\"tipodoc\">' + (jQuery('#tipodoc').val() || '') + '</div>'); jQuery('#tipodoc-multi-selection-help').hide();\n";
		$jsReadOnly .= "\tjQuery('#doc').replaceWith('<div class=\"form-control-static\" id=\"doc\">' + (jQuery('#doc').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#nombre').replaceWith('<div class=\"form-control-static\" id=\"nombre\">' + (jQuery('#nombre').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#genero').replaceWith('<div class=\"form-control-static\" id=\"genero\">' + (jQuery('#genero').val() || '') + '</div>'); jQuery('#genero-multi-selection-help').hide();\n";
		$jsReadOnly .= "\tjQuery('#nacimiento').prop('readonly', true);\n";
		$jsReadOnly .= "\tjQuery('#nacimientoDay, #nacimientoMonth, #nacimientoYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#edad').replaceWith('<div class=\"form-control-static\" id=\"edad\">' + (jQuery('#edad').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#telefono').replaceWith('<div class=\"form-control-static\" id=\"telefono\">' + (jQuery('#telefono').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#regimen').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#regimen_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#eps').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#eps_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#embarazo').replaceWith('<div class=\"form-control-static\" id=\"embarazo\">' + (jQuery('#embarazo').val() || '') + '</div>'); jQuery('#embarazo-multi-selection-help').hide();\n";
		$jsReadOnly .= "\tjQuery('#patologia').prop('disabled', true);\n";
		$jsReadOnly .= "\tjQuery('#fallecido').prop('disabled', true);\n";
		$jsReadOnly .= "\tjQuery('#cual').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#cual_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#atencion').replaceWith('<div class=\"form-control-static\" id=\"atencion\">' + (jQuery('#atencion').val() || '') + '</div>'); jQuery('#atencion-multi-selection-help').hide();\n";
		$jsReadOnly .= "\tjQuery('#s2id_atencion').remove();\n";
		$jsReadOnly .= "\tjQuery('#tratamiento').replaceWith('<div class=\"form-control-static\" id=\"tratamiento\">' + (jQuery('#tratamiento').val() || '') + '</div>'); jQuery('#tratamiento-multi-selection-help').hide();\n";
		$jsReadOnly .= "\tjQuery('#medicamentos').replaceWith('<div class=\"form-control-static\" id=\"medicamentos\">' + (jQuery('#medicamentos').val() || '') + '</div>'); jQuery('#medicamentos-multi-selection-help').hide();\n";
		$jsReadOnly .= "\tjQuery('#vigilancia').replaceWith('<div class=\"form-control-static\" id=\"vigilancia\">' + (jQuery('#vigilancia').val() || '') + '</div>'); jQuery('#vigilancia-multi-selection-help').hide();\n";
		$jsReadOnly .= "\tjQuery('#percepcion').replaceWith('<div class=\"form-control-static\" id=\"percepcion\">' + (jQuery('#percepcion').val() || '') + '</div>'); jQuery('#percepcion-multi-selection-help').hide();\n";
		$jsReadOnly .= "\tjQuery('#medicinageneral').prop('disabled', true);\n";
		$jsReadOnly .= "\tjQuery('#oportunidad').replaceWith('<div class=\"form-control-static\" id=\"oportunidad\">' + (jQuery('#oportunidad').val() || '') + '</div>'); jQuery('#oportunidad-multi-selection-help').hide();\n";
		$jsReadOnly .= "\tjQuery('#observacion').replaceWith('<div class=\"form-control-static\" id=\"observacion\">' + (jQuery('#observacion').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#status').replaceWith('<div class=\"form-control-static\" id=\"status\">' + (jQuery('#status').val() || '') + '</div>'); jQuery('#status-multi-selection-help').hide();\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	} elseif(($AllowInsert && !$selected_id) || ($AllowUpdate && $selected_id)) {
		$jsEditable = "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(fecha)%%>', ($selected_id && !$arrPerm[3] ? '<div class="form-control-static">' . $combo_fecha->GetHTML(true) . '</div>' : $combo_fecha->GetHTML()), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(fecha)%%>', $combo_fecha->GetHTML(true), $templateCode);
	$templateCode = str_replace('<%%COMBO(tipodoc)%%>', $combo_tipodoc->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(tipodoc)%%>', $combo_tipodoc->SelectedData, $templateCode);
	$templateCode = str_replace('<%%COMBO(genero)%%>', $combo_genero->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(genero)%%>', $combo_genero->SelectedData, $templateCode);
	$templateCode = str_replace('<%%COMBO(nacimiento)%%>', ($selected_id && !$arrPerm[3] ? '<div class="form-control-static">' . $combo_nacimiento->GetHTML(true) . '</div>' : $combo_nacimiento->GetHTML()), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(nacimiento)%%>', $combo_nacimiento->GetHTML(true), $templateCode);
	$templateCode = str_replace('<%%COMBO(regimen)%%>', $combo_regimen->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(regimen)%%>', $combo_regimen->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(regimen)%%>', urlencode($combo_regimen->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(eps)%%>', $combo_eps->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(eps)%%>', $combo_eps->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(eps)%%>', urlencode($combo_eps->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(embarazo)%%>', $combo_embarazo->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(embarazo)%%>', $combo_embarazo->SelectedData, $templateCode);
	$templateCode = str_replace('<%%COMBO(cual)%%>', $combo_cual->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(cual)%%>', $combo_cual->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(cual)%%>', urlencode($combo_cual->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(atencion)%%>', $combo_atencion->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(atencion)%%>', $combo_atencion->SelectedData, $templateCode);
	$templateCode = str_replace('<%%COMBO(tratamiento)%%>', $combo_tratamiento->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(tratamiento)%%>', $combo_tratamiento->SelectedData, $templateCode);
	$templateCode = str_replace('<%%COMBO(medicamentos)%%>', $combo_medicamentos->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(medicamentos)%%>', $combo_medicamentos->SelectedData, $templateCode);
	$templateCode = str_replace('<%%COMBO(vigilancia)%%>', $combo_vigilancia->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(vigilancia)%%>', $combo_vigilancia->SelectedData, $templateCode);
	$templateCode = str_replace('<%%COMBO(percepcion)%%>', $combo_percepcion->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(percepcion)%%>', $combo_percepcion->SelectedData, $templateCode);
	$templateCode = str_replace('<%%COMBO(oportunidad)%%>', $combo_oportunidad->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(oportunidad)%%>', $combo_oportunidad->SelectedData, $templateCode);
	$templateCode = str_replace('<%%COMBO(status)%%>', $combo_status->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(status)%%>', $combo_status->SelectedData, $templateCode);

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array('regimen' => array('regimenes', 'Regimen'), 'eps' => array('eps', 'EPS'), 'cual' => array('cie10', 'Cual?'), );
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !$_REQUEST['Embedded']*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(fecha)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(tipodoc)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(doc)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(nombre)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(genero)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(nacimiento)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(edad)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(telefono)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(regimen)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(eps)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(embarazo)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(patologia)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(fallecido)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(cual)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(atencion)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(tratamiento)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(medicamentos)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(vigilancia)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(percepcion)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(medicinageneral)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(oportunidad)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(observacion)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(status)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(responsable)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(periodo)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(asignado)%%>', '', $templateCode);

	// process values
	if($selected_id) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		$templateCode = str_replace('<%%VALUE(fecha)%%>', @date('d/m/Y', @strtotime(html_attr($row['fecha']))), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fecha)%%>', urlencode(@date('d/m/Y', @strtotime(html_attr($urow['fecha'])))), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(tipodoc)%%>', safe_html($urow['tipodoc']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(tipodoc)%%>', html_attr($row['tipodoc']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(tipodoc)%%>', urlencode($urow['tipodoc']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(doc)%%>', safe_html($urow['doc']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(doc)%%>', html_attr($row['doc']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(doc)%%>', urlencode($urow['doc']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(nombre)%%>', safe_html($urow['nombre']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(nombre)%%>', html_attr($row['nombre']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(nombre)%%>', urlencode($urow['nombre']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(genero)%%>', safe_html($urow['genero']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(genero)%%>', html_attr($row['genero']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(genero)%%>', urlencode($urow['genero']), $templateCode);
		$templateCode = str_replace('<%%VALUE(nacimiento)%%>', @date('d/m/Y', @strtotime(html_attr($row['nacimiento']))), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(nacimiento)%%>', urlencode(@date('d/m/Y', @strtotime(html_attr($urow['nacimiento'])))), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(edad)%%>', safe_html($urow['edad']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(edad)%%>', html_attr($row['edad']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(edad)%%>', urlencode($urow['edad']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(telefono)%%>', safe_html($urow['telefono']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(telefono)%%>', html_attr($row['telefono']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(telefono)%%>', urlencode($urow['telefono']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(regimen)%%>', safe_html($urow['regimen']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(regimen)%%>', html_attr($row['regimen']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(regimen)%%>', urlencode($urow['regimen']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(eps)%%>', safe_html($urow['eps']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(eps)%%>', html_attr($row['eps']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(eps)%%>', urlencode($urow['eps']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(embarazo)%%>', safe_html($urow['embarazo']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(embarazo)%%>', html_attr($row['embarazo']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(embarazo)%%>', urlencode($urow['embarazo']), $templateCode);
		$templateCode = str_replace('<%%CHECKED(patologia)%%>', ($row['patologia'] ? "checked" : ""), $templateCode);
		$templateCode = str_replace('<%%CHECKED(fallecido)%%>', ($row['fallecido'] ? "checked" : ""), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(cual)%%>', safe_html($urow['cual']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(cual)%%>', html_attr($row['cual']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(cual)%%>', urlencode($urow['cual']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(atencion)%%>', safe_html($urow['atencion']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(atencion)%%>', html_attr($row['atencion']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(atencion)%%>', urlencode($urow['atencion']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(tratamiento)%%>', safe_html($urow['tratamiento']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(tratamiento)%%>', html_attr($row['tratamiento']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(tratamiento)%%>', urlencode($urow['tratamiento']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(medicamentos)%%>', safe_html($urow['medicamentos']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(medicamentos)%%>', html_attr($row['medicamentos']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(medicamentos)%%>', urlencode($urow['medicamentos']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(vigilancia)%%>', safe_html($urow['vigilancia']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(vigilancia)%%>', html_attr($row['vigilancia']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(vigilancia)%%>', urlencode($urow['vigilancia']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(percepcion)%%>', safe_html($urow['percepcion']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(percepcion)%%>', html_attr($row['percepcion']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(percepcion)%%>', urlencode($urow['percepcion']), $templateCode);
		$templateCode = str_replace('<%%CHECKED(medicinageneral)%%>', ($row['medicinageneral'] ? "checked" : ""), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(oportunidad)%%>', safe_html($urow['oportunidad']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(oportunidad)%%>', html_attr($row['oportunidad']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(oportunidad)%%>', urlencode($urow['oportunidad']), $templateCode);
		if($dvprint || (!$AllowUpdate && !$AllowInsert)) {
			$templateCode = str_replace('<%%VALUE(observacion)%%>', safe_html($urow['observacion']), $templateCode);
		} else {
			$templateCode = str_replace('<%%VALUE(observacion)%%>', safe_html($urow['observacion'], true), $templateCode);
		}
		$templateCode = str_replace('<%%URLVALUE(observacion)%%>', urlencode($urow['observacion']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(status)%%>', safe_html($urow['status']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(status)%%>', html_attr($row['status']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(status)%%>', urlencode($urow['status']), $templateCode);
		$templateCode = str_replace('<%%VALUE(responsable)%%>', safe_html($urow['responsable']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(responsable)%%>', urlencode($urow['responsable']), $templateCode);
		$templateCode = str_replace('<%%VALUE(periodo)%%>', safe_html($urow['periodo']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(periodo)%%>', urlencode($urow['periodo']), $templateCode);
		$templateCode = str_replace('<%%VALUE(asignado)%%>', safe_html($urow['asignado']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(asignado)%%>', urlencode($urow['asignado']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(fecha)%%>', '<%%editingDateTime%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fecha)%%>', urlencode('<%%editingDateTime%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(tipodoc)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(tipodoc)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(doc)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(doc)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(nombre)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(nombre)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(genero)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(genero)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(nacimiento)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(nacimiento)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(edad)%%>', 'Edad', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(edad)%%>', urlencode('Edad'), $templateCode);
		$templateCode = str_replace('<%%VALUE(telefono)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(telefono)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(regimen)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(regimen)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(eps)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(eps)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(embarazo)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(embarazo)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%CHECKED(patologia)%%>', '', $templateCode);
		$templateCode = str_replace('<%%CHECKED(fallecido)%%>', '', $templateCode);
		$templateCode = str_replace('<%%VALUE(cual)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(cual)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(atencion)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(atencion)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(tratamiento)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(tratamiento)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(medicamentos)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(medicamentos)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(vigilancia)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(vigilancia)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(percepcion)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(percepcion)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%CHECKED(medicinageneral)%%>', '', $templateCode);
		$templateCode = str_replace('<%%VALUE(oportunidad)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(oportunidad)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(observacion)%%>', 'SIN OBSERVACION', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(observacion)%%>', urlencode('SIN OBSERVACION'), $templateCode);
		$templateCode = str_replace('<%%VALUE(status)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(status)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(responsable)%%>', '<%%editorUsername%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(responsable)%%>', urlencode('<%%editorUsername%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(periodo)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(periodo)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(asignado)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(asignado)%%>', urlencode(''), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('covid');
	if($selected_id) {
		$jdata = get_joined_record('covid', $selected_id);
		if($jdata === false) $jdata = get_defaults('covid');
		$rdata = $row;
	}
	$templateCode .= loadView('covid-ajax-cache', array('rdata' => $rdata, 'jdata' => $jdata));

	// hook: covid_dv
	if(function_exists('covid_dv')) {
		$args=[];
		covid_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}