<?php
// This script and data application were generated by AppGini 5.97
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir = dirname(__FILE__);
	include_once("{$currDir}/lib.php");
	@include_once("{$currDir}/hooks/ips.php");
	include_once("{$currDir}/ips_dml.php");

	// mm: can the current member access this page?
	$perm = getTablePermissions('ips');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'ips';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`ips`.`nombre`" => "nombre",
		"`ips`.`municipio`" => "municipio",
		"`ips`.`correo`" => "correo",
		"`ips`.`direccion`" => "direccion",
		"`ips`.`telefono`" => "telefono",
		"`ips`.`gerente`" => "gerente",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => 1,
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`ips`.`nombre`" => "nombre",
		"`ips`.`municipio`" => "municipio",
		"`ips`.`correo`" => "correo",
		"`ips`.`direccion`" => "direccion",
		"`ips`.`telefono`" => "telefono",
		"`ips`.`gerente`" => "gerente",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`ips`.`nombre`" => "Nombre",
		"`ips`.`municipio`" => "Municipio",
		"`ips`.`correo`" => "Correo",
		"`ips`.`direccion`" => "Direccion",
		"`ips`.`telefono`" => "Telefono",
		"`ips`.`gerente`" => "Gerente",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`ips`.`nombre`" => "nombre",
		"`ips`.`municipio`" => "municipio",
		"`ips`.`correo`" => "correo",
		"`ips`.`direccion`" => "direccion",
		"`ips`.`telefono`" => "telefono",
		"`ips`.`gerente`" => "gerente",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = [];

	$x->QueryFrom = "`ips` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = (getLoggedAdmin() !== false);
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'ips_view.php';
	$x->RedirectAfterInsert = 'ips_view.php?SelectedID=#ID#';
	$x->TableTitle = 'IPS';
	$x->TableIcon = 'resources/table_icons/application_home.png';
	$x->PrimaryKey = '`ips`.`nombre`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Nombre', 'Municipio', 'Correo', 'Direccion', 'Telefono', 'Gerente', ];
	$x->ColFieldName = ['nombre', 'municipio', 'correo', 'direccion', 'telefono', 'gerente', ];
	$x->ColNumber  = [1, 2, 3, 4, 5, 6, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/ips_templateTV.html';
	$x->SelectedTemplate = 'templates/ips_templateTVS.html';
	$x->TemplateDV = 'templates/ips_templateDV.html';
	$x->TemplateDVP = 'templates/ips_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: ips_init
	$render = true;
	if(function_exists('ips_init')) {
		$args = [];
		$render = ips_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: ips_header
	$headerCode = '';
	if(function_exists('ips_header')) {
		$args = [];
		$headerCode = ips_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once("{$currDir}/header.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/header.php");
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: ips_footer
	$footerCode = '';
	if(function_exists('ips_footer')) {
		$args = [];
		$footerCode = ips_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once("{$currDir}/footer.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/footer.php");
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
