<?php
// This script and data application were generated by AppGini 5.97
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir = dirname(__FILE__);
	include_once("{$currDir}/lib.php");
	@include_once("{$currDir}/hooks/oficios.php");
	include_once("{$currDir}/oficios_dml.php");

	// mm: can the current member access this page?
	$perm = getTablePermissions('oficios');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'oficios';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`oficios`.`id`" => "id",
		"IF(    CHAR_LENGTH(`pqr1`.`oficio`), CONCAT_WS('',   `pqr1`.`oficio`), '') /* N&#250;mero */" => "idpqr",
		"`oficios`.`oficio`" => "oficio",
		"`oficios`.`nombre`" => "nombre",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`oficios`.`id`',
		2 => '`pqr1`.`oficio`',
		3 => 3,
		4 => 4,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`oficios`.`id`" => "id",
		"IF(    CHAR_LENGTH(`pqr1`.`oficio`), CONCAT_WS('',   `pqr1`.`oficio`), '') /* N&#250;mero */" => "idpqr",
		"`oficios`.`oficio`" => "oficio",
		"`oficios`.`nombre`" => "nombre",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`oficios`.`id`" => "ID",
		"IF(    CHAR_LENGTH(`pqr1`.`oficio`), CONCAT_WS('',   `pqr1`.`oficio`), '') /* N&#250;mero */" => "N&#250;mero",
		"`oficios`.`oficio`" => "Oficio",
		"`oficios`.`nombre`" => "Nombre",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`oficios`.`id`" => "id",
		"IF(    CHAR_LENGTH(`pqr1`.`oficio`), CONCAT_WS('',   `pqr1`.`oficio`), '') /* N&#250;mero */" => "idpqr",
		"`oficios`.`oficio`" => "oficio",
		"`oficios`.`nombre`" => "nombre",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['idpqr' => 'N&#250;mero', ];

	$x->QueryFrom = "`oficios` LEFT JOIN `pqr` as pqr1 ON `pqr1`.`id`=`oficios`.`idpqr` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'oficios_view.php';
	$x->RedirectAfterInsert = 'oficios_view.php?SelectedID=#ID#';
	$x->TableTitle = 'Oficios';
	$x->TableIcon = 'resources/table_icons/email_open.png';
	$x->PrimaryKey = '`oficios`.`id`';

	$x->ColWidth = [150, 150, ];
	$x->ColCaption = ['N&#250;mero', 'Nombre', ];
	$x->ColFieldName = ['idpqr', 'nombre', ];
	$x->ColNumber  = [2, 4, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/oficios_templateTV.html';
	$x->SelectedTemplate = 'templates/oficios_templateTVS.html';
	$x->TemplateDV = 'templates/oficios_templateDV.html';
	$x->TemplateDVP = 'templates/oficios_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = true;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: oficios_init
	$render = true;
	if(function_exists('oficios_init')) {
		$args = [];
		$render = oficios_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: oficios_header
	$headerCode = '';
	if(function_exists('oficios_header')) {
		$args = [];
		$headerCode = oficios_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once("{$currDir}/header.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/header.php");
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: oficios_footer
	$footerCode = '';
	if(function_exists('oficios_footer')) {
		$args = [];
		$footerCode = oficios_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once("{$currDir}/footer.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/footer.php");
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
