<?php
// This script and data application were generated by AppGini 5.97
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir = dirname(__FILE__);
	include_once("{$currDir}/lib.php");
	@include_once("{$currDir}/hooks/oportunidad.php");
	include_once("{$currDir}/oportunidad_dml.php");

	// mm: can the current member access this page?
	$perm = getTablePermissions('oportunidad');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'oportunidad';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`oportunidad`.`id`" => "id",
		"`oportunidad`.`tipodoc`" => "tipodoc",
		"`oportunidad`.`doc`" => "doc",
		"`oportunidad`.`nombres`" => "nombres",
		"`oportunidad`.`apellidos`" => "apellidos",
		"IF(    CHAR_LENGTH(`regimenes1`.`nombre`), CONCAT_WS('',   `regimenes1`.`nombre`), '') /* Regimen */" => "regimen",
		"IF(    CHAR_LENGTH(`eps1`.`razonsocial`), CONCAT_WS('',   `eps1`.`razonsocial`), '') /* Eps */" => "eps",
		"if(`oportunidad`.`fechanac`,date_format(`oportunidad`.`fechanac`,'%d/%m/%Y'),'')" => "fechanac",
		"`oportunidad`.`edad`" => "edad",
		"`oportunidad`.`atencionreq`" => "atencionreq",
		"if(`oportunidad`.`fechaorden`,date_format(`oportunidad`.`fechaorden`,'%d/%m/%Y'),'')" => "fechaorden",
		"if(`oportunidad`.`fechacita`,date_format(`oportunidad`.`fechacita`,'%d/%m/%Y'),'')" => "fechacita",
		"`oportunidad`.`calificacion`" => "calificacion",
		"`oportunidad`.`observaciones`" => "observaciones",
		"`oportunidad`.`asignado`" => "asignado",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`oportunidad`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => '`regimenes1`.`nombre`',
		7 => '`eps1`.`razonsocial`',
		8 => '`oportunidad`.`fechanac`',
		9 => 9,
		10 => 10,
		11 => '`oportunidad`.`fechaorden`',
		12 => '`oportunidad`.`fechacita`',
		13 => 13,
		14 => 14,
		15 => 15,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`oportunidad`.`id`" => "id",
		"`oportunidad`.`tipodoc`" => "tipodoc",
		"`oportunidad`.`doc`" => "doc",
		"`oportunidad`.`nombres`" => "nombres",
		"`oportunidad`.`apellidos`" => "apellidos",
		"IF(    CHAR_LENGTH(`regimenes1`.`nombre`), CONCAT_WS('',   `regimenes1`.`nombre`), '') /* Regimen */" => "regimen",
		"IF(    CHAR_LENGTH(`eps1`.`razonsocial`), CONCAT_WS('',   `eps1`.`razonsocial`), '') /* Eps */" => "eps",
		"if(`oportunidad`.`fechanac`,date_format(`oportunidad`.`fechanac`,'%d/%m/%Y'),'')" => "fechanac",
		"`oportunidad`.`edad`" => "edad",
		"`oportunidad`.`atencionreq`" => "atencionreq",
		"if(`oportunidad`.`fechaorden`,date_format(`oportunidad`.`fechaorden`,'%d/%m/%Y'),'')" => "fechaorden",
		"if(`oportunidad`.`fechacita`,date_format(`oportunidad`.`fechacita`,'%d/%m/%Y'),'')" => "fechacita",
		"`oportunidad`.`calificacion`" => "calificacion",
		"`oportunidad`.`observaciones`" => "observaciones",
		"`oportunidad`.`asignado`" => "asignado",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`oportunidad`.`id`" => "ID",
		"`oportunidad`.`tipodoc`" => "Tipo de Documento",
		"`oportunidad`.`doc`" => "Numero de Documento",
		"`oportunidad`.`nombres`" => "Nombres",
		"`oportunidad`.`apellidos`" => "Apellidos",
		"IF(    CHAR_LENGTH(`regimenes1`.`nombre`), CONCAT_WS('',   `regimenes1`.`nombre`), '') /* Regimen */" => "Regimen",
		"IF(    CHAR_LENGTH(`eps1`.`razonsocial`), CONCAT_WS('',   `eps1`.`razonsocial`), '') /* Eps */" => "Eps",
		"`oportunidad`.`fechanac`" => "Fecha de Nacimiento",
		"`oportunidad`.`edad`" => "Edad",
		"`oportunidad`.`atencionreq`" => "La ultima atenci&#243;n requerida por parte de su EPS, a que especialidad pertenc&#237;a?",
		"`oportunidad`.`fechaorden`" => "Cuando fue solicitada la ultima atenci&#243;n?",
		"`oportunidad`.`fechacita`" => "Cuando le fue realizada efectivamente la ultima atenci&#243;n?",
		"`oportunidad`.`calificacion`" => "Que calificaci&#243;n le da al servicio brindado por su EPS?",
		"`oportunidad`.`observaciones`" => "Tiene alguna observaci&#243;n?",
		"`oportunidad`.`asignado`" => "Asignado",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`oportunidad`.`id`" => "id",
		"`oportunidad`.`tipodoc`" => "tipodoc",
		"`oportunidad`.`doc`" => "doc",
		"`oportunidad`.`nombres`" => "nombres",
		"`oportunidad`.`apellidos`" => "apellidos",
		"IF(    CHAR_LENGTH(`regimenes1`.`nombre`), CONCAT_WS('',   `regimenes1`.`nombre`), '') /* Regimen */" => "regimen",
		"IF(    CHAR_LENGTH(`eps1`.`razonsocial`), CONCAT_WS('',   `eps1`.`razonsocial`), '') /* Eps */" => "eps",
		"if(`oportunidad`.`fechanac`,date_format(`oportunidad`.`fechanac`,'%d/%m/%Y'),'')" => "fechanac",
		"`oportunidad`.`edad`" => "edad",
		"`oportunidad`.`atencionreq`" => "atencionreq",
		"if(`oportunidad`.`fechaorden`,date_format(`oportunidad`.`fechaorden`,'%d/%m/%Y'),'')" => "fechaorden",
		"if(`oportunidad`.`fechacita`,date_format(`oportunidad`.`fechacita`,'%d/%m/%Y'),'')" => "fechacita",
		"`oportunidad`.`calificacion`" => "calificacion",
		"`oportunidad`.`observaciones`" => "observaciones",
		"`oportunidad`.`asignado`" => "asignado",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['regimen' => 'Regimen', 'eps' => 'Eps', ];

	$x->QueryFrom = "`oportunidad` LEFT JOIN `regimenes` as regimenes1 ON `regimenes1`.`nombre`=`oportunidad`.`regimen` LEFT JOIN `eps` as eps1 ON `eps1`.`razonsocial`=`oportunidad`.`eps` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'oportunidad_view.php';
	$x->RedirectAfterInsert = 'oportunidad_view.php?SelectedID=#ID#';
	$x->TableTitle = 'Oportunidad';
	$x->TableIcon = 'resources/table_icons/time.png';
	$x->PrimaryKey = '`oportunidad`.`id`';

	$x->ColWidth = [150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Tipo de Documento', 'Numero de Documento', 'Nombres', 'Apellidos', 'Regimen', 'Eps', 'Fecha de Nacimiento', 'Edad', 'La ultima atenci&#243;n requerida por parte de su EPS, a que especialidad pertenc&#237;a?', 'Cuando fue solicitada la ultima atenci&#243;n?', 'Cuando le fue realizada efectivamente la ultima atenci&#243;n?', 'Que calificaci&#243;n le da al servicio brindado por su EPS?', 'Tiene alguna observaci&#243;n?', 'Asignado', ];
	$x->ColFieldName = ['tipodoc', 'doc', 'nombres', 'apellidos', 'regimen', 'eps', 'fechanac', 'edad', 'atencionreq', 'fechaorden', 'fechacita', 'calificacion', 'observaciones', 'asignado', ];
	$x->ColNumber  = [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/oportunidad_templateTV.html';
	$x->SelectedTemplate = 'templates/oportunidad_templateTVS.html';
	$x->TemplateDV = 'templates/oportunidad_templateDV.html';
	$x->TemplateDVP = 'templates/oportunidad_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = true;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: oportunidad_init
	$render = true;
	if(function_exists('oportunidad_init')) {
		$args = [];
		$render = oportunidad_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: oportunidad_header
	$headerCode = '';
	if(function_exists('oportunidad_header')) {
		$args = [];
		$headerCode = oportunidad_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once("{$currDir}/header.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/header.php");
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: oportunidad_footer
	$footerCode = '';
	if(function_exists('oportunidad_footer')) {
		$args = [];
		$footerCode = oportunidad_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once("{$currDir}/footer.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/footer.php");
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
