<?php

// Data functions (insert, update, delete, form) for table oportunidad

// This script and data application were generated by AppGini 5.97
// Download AppGini for free from https://bigprof.com/appgini/download/

function oportunidad_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('oportunidad');
	if(!$arrPerm['insert']) return false;

	$data = [
		'tipodoc' => Request::val('tipodoc', ''),
		'doc' => Request::val('doc', ''),
		'nombres' => Request::val('nombres', ''),
		'apellidos' => Request::val('apellidos', ''),
		'regimen' => Request::lookup('regimen', ''),
		'eps' => Request::lookup('eps', ''),
		'fechanac' => Request::dateComponents('fechanac', ''),
		'edad' => Request::val('edad', ''),
		'atencionreq' => Request::val('atencionreq', ''),
		'fechaorden' => Request::dateComponents('fechaorden', ''),
		'fechacita' => Request::dateComponents('fechacita', ''),
		'calificacion' => Request::val('calificacion', ''),
		'observaciones' => br2nl(Request::val('observaciones', '')),
	];

	if($data['tipodoc'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Tipo de Documento': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['doc'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Numero de Documento': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['nombres'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Nombres': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['apellidos'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Apellidos': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['regimen'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Regimen': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['eps'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Eps': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['fechanac'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Fecha de Nacimiento': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['atencionreq'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'La ultima atenci&#243;n requerida por parte de su EPS, a que especialidad pertenc&#237;a?': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['calificacion'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Que calificaci&#243;n le da al servicio brindado por su EPS?': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}

	// hook: oportunidad_before_insert
	if(function_exists('oportunidad_before_insert')) {
		$args = [];
		if(!oportunidad_before_insert($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('oportunidad', backtick_keys_once($data), $error);
	if($error)
		die("{$error}<br><a href=\"#\" onclick=\"history.go(-1);\">{$Translation['< back']}</a>");

	$recID = db_insert_id(db_link());

	update_calc_fields('oportunidad', $recID, calculated_fields()['oportunidad']);

	// hook: oportunidad_after_insert
	if(function_exists('oportunidad_after_insert')) {
		$res = sql("SELECT * FROM `oportunidad` WHERE `id`='" . makeSafe($recID, false) . "' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=[];
		if(!oportunidad_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	set_record_owner('oportunidad', $recID, getLoggedMemberID());

	// if this record is a copy of another record, copy children if applicable
	if(!empty($_REQUEST['SelectedID'])) oportunidad_copy_children($recID, $_REQUEST['SelectedID']);

	return $recID;
}

function oportunidad_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function oportunidad_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('oportunidad', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: oportunidad_before_delete
	if(function_exists('oportunidad_before_delete')) {
		$args = [];
		if(!oportunidad_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: '' 
			);
	}

	sql("DELETE FROM `oportunidad` WHERE `id`='{$selected_id}'", $eo);

	// hook: oportunidad_after_delete
	if(function_exists('oportunidad_after_delete')) {
		$args = [];
		oportunidad_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='oportunidad' AND `pkValue`='{$selected_id}'", $eo);
}

function oportunidad_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('oportunidad', $selected_id, 'edit')) return false;

	$data = [
		'tipodoc' => Request::val('tipodoc', ''),
		'doc' => Request::val('doc', ''),
		'nombres' => Request::val('nombres', ''),
		'apellidos' => Request::val('apellidos', ''),
		'regimen' => Request::lookup('regimen', ''),
		'eps' => Request::lookup('eps', ''),
		'fechanac' => Request::dateComponents('fechanac', ''),
		'edad' => Request::val('edad', ''),
		'atencionreq' => Request::val('atencionreq', ''),
		'fechaorden' => Request::dateComponents('fechaorden', ''),
		'fechacita' => Request::dateComponents('fechacita', ''),
		'calificacion' => Request::val('calificacion', ''),
		'observaciones' => br2nl(Request::val('observaciones', '')),
	];

	if($data['tipodoc'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Tipo de Documento': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['doc'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Numero de Documento': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['nombres'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Nombres': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['apellidos'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Apellidos': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['regimen'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Regimen': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['eps'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Eps': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['fechanac'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Fecha de Nacimiento': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['atencionreq'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'La ultima atenci&#243;n requerida por parte de su EPS, a que especialidad pertenc&#237;a?': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['calificacion'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Que calificaci&#243;n le da al servicio brindado por su EPS?': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	// get existing values
	$old_data = getRecord('oportunidad', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: oportunidad_before_update
	if(function_exists('oportunidad_before_update')) {
		$args = ['old_data' => $old_data];
		if(!oportunidad_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'oportunidad', 
		backtick_keys_once($set), 
		['`id`' => $selected_id], 
		$error_message
	)) {
		echo $error_message;
		echo '<a href="oportunidad_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	$eo = ['silentErrors' => true];

	update_calc_fields('oportunidad', $data['selectedID'], calculated_fields()['oportunidad']);

	// hook: oportunidad_after_update
	if(function_exists('oportunidad_after_update')) {
		$res = sql("SELECT * FROM `oportunidad` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['id'];
		$args = ['old_data' => $old_data];
		if(!oportunidad_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update ownership data
	sql("UPDATE `membership_userrecords` SET `dateUpdated`='" . time() . "' WHERE `tableName`='oportunidad' AND `pkValue`='" . makeSafe($selected_id) . "'", $eo);
}

function oportunidad_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0, $TemplateDV = '', $TemplateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm = getTablePermissions('oportunidad');
	if(!$arrPerm['insert'] && $selected_id=='') return $Translation['tableAccessDenied'];
	$AllowInsert = ($arrPerm['insert'] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != '') {
		$dvprint = true;
	}

	$filterer_regimen = thisOr($_REQUEST['filterer_regimen'], '');
	$filterer_eps = thisOr($_REQUEST['filterer_eps'], '');

	// populate filterers, starting from children to grand-parents
	if($filterer_eps && !$filterer_regimen) $filterer_regimen = sqlValue("select regimen from eps where razonsocial='" . makeSafe($filterer_eps) . "'");

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: tipodoc
	$combo_tipodoc = new Combo;
	$combo_tipodoc->ListType = 0;
	$combo_tipodoc->MultipleSeparator = ', ';
	$combo_tipodoc->ListBoxHeight = 10;
	$combo_tipodoc->RadiosPerLine = 1;
	if(is_file(dirname(__FILE__).'/hooks/oportunidad.tipodoc.csv')) {
		$tipodoc_data = addslashes(implode('', @file(dirname(__FILE__).'/hooks/oportunidad.tipodoc.csv')));
		$combo_tipodoc->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions($tipodoc_data)));
		$combo_tipodoc->ListData = $combo_tipodoc->ListItem;
	} else {
		$combo_tipodoc->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions(";;RC;;TI;;CC;;PAS;;PEP;;AS;;Extranjero;;Otro")));
		$combo_tipodoc->ListData = $combo_tipodoc->ListItem;
	}
	$combo_tipodoc->SelectName = 'tipodoc';
	$combo_tipodoc->AllowNull = false;
	// combobox: regimen
	$combo_regimen = new DataCombo;
	// combobox: eps, filterable by: regimen
	$combo_eps = new DataCombo;
	// combobox: fechanac
	$combo_fechanac = new DateCombo;
	$combo_fechanac->DateFormat = "dmy";
	$combo_fechanac->MinYear = 1900;
	$combo_fechanac->MaxYear = 2100;
	$combo_fechanac->DefaultDate = parseMySQLDate('', '');
	$combo_fechanac->MonthNames = $Translation['month names'];
	$combo_fechanac->NamePrefix = 'fechanac';
	// combobox: atencionreq
	$combo_atencionreq = new Combo;
	$combo_atencionreq->ListType = 0;
	$combo_atencionreq->MultipleSeparator = ', ';
	$combo_atencionreq->ListBoxHeight = 10;
	$combo_atencionreq->RadiosPerLine = 1;
	if(is_file(dirname(__FILE__).'/hooks/oportunidad.atencionreq.csv')) {
		$atencionreq_data = addslashes(implode('', @file(dirname(__FILE__).'/hooks/oportunidad.atencionreq.csv')));
		$combo_atencionreq->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions($atencionreq_data)));
		$combo_atencionreq->ListData = $combo_atencionreq->ListItem;
	} else {
		$combo_atencionreq->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions(";;Medicina General;;Odontologia;;Promoci&#243;n y Prevenci&#243;n;;Urgencias;;Oftalmolog&#237;a;;Pediatria;;Ortopedia;;Cirug&#237;a;;Urolog&#237;a;;Genecolog&#237;a;;Otorrinolaringolog&#237;a;;Dermatologia;;Otro;;No he requerido")));
		$combo_atencionreq->ListData = $combo_atencionreq->ListItem;
	}
	$combo_atencionreq->SelectName = 'atencionreq';
	$combo_atencionreq->AllowNull = false;
	// combobox: fechaorden
	$combo_fechaorden = new DateCombo;
	$combo_fechaorden->DateFormat = "dmy";
	$combo_fechaorden->MinYear = 1900;
	$combo_fechaorden->MaxYear = 2100;
	$combo_fechaorden->DefaultDate = parseMySQLDate('', '');
	$combo_fechaorden->MonthNames = $Translation['month names'];
	$combo_fechaorden->NamePrefix = 'fechaorden';
	// combobox: fechacita
	$combo_fechacita = new DateCombo;
	$combo_fechacita->DateFormat = "dmy";
	$combo_fechacita->MinYear = 1900;
	$combo_fechacita->MaxYear = 2100;
	$combo_fechacita->DefaultDate = parseMySQLDate('', '');
	$combo_fechacita->MonthNames = $Translation['month names'];
	$combo_fechacita->NamePrefix = 'fechacita';
	// combobox: calificacion
	$combo_calificacion = new Combo;
	$combo_calificacion->ListType = 0;
	$combo_calificacion->MultipleSeparator = ', ';
	$combo_calificacion->ListBoxHeight = 10;
	$combo_calificacion->RadiosPerLine = 1;
	if(is_file(dirname(__FILE__).'/hooks/oportunidad.calificacion.csv')) {
		$calificacion_data = addslashes(implode('', @file(dirname(__FILE__).'/hooks/oportunidad.calificacion.csv')));
		$combo_calificacion->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions($calificacion_data)));
		$combo_calificacion->ListData = $combo_calificacion->ListItem;
	} else {
		$combo_calificacion->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions(";;EXCELENTE;;BUENO;;REGULAR;;MALO")));
		$combo_calificacion->ListData = $combo_calificacion->ListItem;
	}
	$combo_calificacion->SelectName = 'calificacion';
	$combo_calificacion->AllowNull = false;

	if($selected_id) {
		// mm: check member permissions
		if(!$arrPerm['view']) return $Translation['tableAccessDenied'];

		// mm: who is the owner?
		$ownerGroupID = sqlValue("SELECT `groupID` FROM `membership_userrecords` WHERE `tableName`='oportunidad' AND `pkValue`='" . makeSafe($selected_id) . "'");
		$ownerMemberID = sqlValue("SELECT LCASE(`memberID`) FROM `membership_userrecords` WHERE `tableName`='oportunidad' AND `pkValue`='" . makeSafe($selected_id) . "'");

		if($arrPerm['view'] == 1 && getLoggedMemberID() != $ownerMemberID) return $Translation['tableAccessDenied'];
		if($arrPerm['view'] == 2 && getLoggedGroupID() != $ownerGroupID) return $Translation['tableAccessDenied'];

		// can edit?
		$AllowUpdate = 0;
		if(($arrPerm['edit'] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm['edit'] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm['edit'] == 3) {
			$AllowUpdate = 1;
		}

		$res = sql("SELECT * FROM `oportunidad` WHERE `id`='" . makeSafe($selected_id) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'oportunidad_view.php', false);
		}
		$combo_tipodoc->SelectedData = $row['tipodoc'];
		$combo_regimen->SelectedData = $row['regimen'];
		$combo_eps->SelectedData = $row['eps'];
		$combo_fechanac->DefaultDate = $row['fechanac'];
		$combo_atencionreq->SelectedData = $row['atencionreq'];
		$combo_fechaorden->DefaultDate = $row['fechaorden'];
		$combo_fechacita->DefaultDate = $row['fechacita'];
		$combo_calificacion->SelectedData = $row['calificacion'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$combo_tipodoc->SelectedText = ( $_REQUEST['FilterField'][1] == '2' && $_REQUEST['FilterOperator'][1] == '<=>' ? $_REQUEST['FilterValue'][1] : '');
		$combo_regimen->SelectedData = $filterer_regimen;
		$combo_eps->SelectedData = $filterer_eps;
		$combo_atencionreq->SelectedText = ( $_REQUEST['FilterField'][1] == '10' && $_REQUEST['FilterOperator'][1] == '<=>' ? $_REQUEST['FilterValue'][1] : '');
		$combo_calificacion->SelectedText = ( $_REQUEST['FilterField'][1] == '13' && $_REQUEST['FilterOperator'][1] == '<=>' ? $_REQUEST['FilterValue'][1] : '');
	}
	$combo_tipodoc->Render();
	$combo_regimen->HTML = '<span id="regimen-container' . $rnd1 . '"></span><input type="hidden" name="regimen" id="regimen' . $rnd1 . '" value="' . html_attr($combo_regimen->SelectedData) . '">';
	$combo_regimen->MatchText = '<span id="regimen-container-readonly' . $rnd1 . '"></span><input type="hidden" name="regimen" id="regimen' . $rnd1 . '" value="' . html_attr($combo_regimen->SelectedData) . '">';
	$combo_eps->HTML = '<span id="eps-container' . $rnd1 . '"></span><input type="hidden" name="eps" id="eps' . $rnd1 . '" value="' . html_attr($combo_eps->SelectedData) . '">';
	$combo_eps->MatchText = '<span id="eps-container-readonly' . $rnd1 . '"></span><input type="hidden" name="eps" id="eps' . $rnd1 . '" value="' . html_attr($combo_eps->SelectedData) . '">';
	$combo_atencionreq->Render();
	$combo_calificacion->Render();

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_regimen__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['regimen'] : htmlspecialchars($filterer_regimen, ENT_QUOTES)); ?>"};
		AppGini.current_eps__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['eps'] : htmlspecialchars($filterer_eps, ENT_QUOTES)); ?>"};

		jQuery(function() {
			setTimeout(function() {
				if(typeof(regimen_reload__RAND__) == 'function') regimen_reload__RAND__();
				<?php echo (!$AllowUpdate || $dvprint ? 'if(typeof(eps_reload__RAND__) == \'function\') eps_reload__RAND__(AppGini.current_regimen__RAND__.value);' : ''); ?>
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function regimen_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#regimen-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_regimen__RAND__.value, t: 'oportunidad', f: 'regimen' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="regimen"]').val(resp.results[0].id);
							$j('[id=regimen-container-readonly__RAND__]').html('<span id="regimen-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=regimenes_view_parent]').hide(); } else { $j('.btn[id=regimenes_view_parent]').show(); }

						if(typeof(eps_reload__RAND__) == 'function') eps_reload__RAND__(AppGini.current_regimen__RAND__.value);

							if(typeof(regimen_update_autofills__RAND__) == 'function') regimen_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'oportunidad', f: 'regimen' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_regimen__RAND__.value = e.added.id;
				AppGini.current_regimen__RAND__.text = e.added.text;
				$j('[name="regimen"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=regimenes_view_parent]').hide(); } else { $j('.btn[id=regimenes_view_parent]').show(); }

						if(typeof(eps_reload__RAND__) == 'function') eps_reload__RAND__(AppGini.current_regimen__RAND__.value);

				if(typeof(regimen_update_autofills__RAND__) == 'function') regimen_update_autofills__RAND__();
			});

			if(!$j("#regimen-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_regimen__RAND__.value, t: 'oportunidad', f: 'regimen' },
					success: function(resp) {
						$j('[name="regimen"]').val(resp.results[0].id);
						$j('[id=regimen-container-readonly__RAND__]').html('<span id="regimen-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=regimenes_view_parent]').hide(); } else { $j('.btn[id=regimenes_view_parent]').show(); }

						if(typeof(regimen_update_autofills__RAND__) == 'function') regimen_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_regimen__RAND__.value, t: 'oportunidad', f: 'regimen' },
				success: function(resp) {
					$j('[id=regimen-container__RAND__], [id=regimen-container-readonly__RAND__]').html('<span id="regimen-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=regimenes_view_parent]').hide(); } else { $j('.btn[id=regimenes_view_parent]').show(); }

					if(typeof(regimen_update_autofills__RAND__) == 'function') regimen_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function eps_reload__RAND__(filterer_regimen) {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#eps-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { filterer_regimen: filterer_regimen, id: AppGini.current_eps__RAND__.value, t: 'oportunidad', f: 'eps' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="eps"]').val(resp.results[0].id);
							$j('[id=eps-container-readonly__RAND__]').html('<span id="eps-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=eps_view_parent]').hide(); } else { $j('.btn[id=eps_view_parent]').show(); }


							if(typeof(eps_update_autofills__RAND__) == 'function') eps_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { filterer_regimen: filterer_regimen, s: term, p: page, t: 'oportunidad', f: 'eps' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_eps__RAND__.value = e.added.id;
				AppGini.current_eps__RAND__.text = e.added.text;
				$j('[name="eps"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=eps_view_parent]').hide(); } else { $j('.btn[id=eps_view_parent]').show(); }


				if(typeof(eps_update_autofills__RAND__) == 'function') eps_update_autofills__RAND__();
			});

			if(!$j("#eps-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_eps__RAND__.value, t: 'oportunidad', f: 'eps' },
					success: function(resp) {
						$j('[name="eps"]').val(resp.results[0].id);
						$j('[id=eps-container-readonly__RAND__]').html('<span id="eps-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=eps_view_parent]').hide(); } else { $j('.btn[id=eps_view_parent]').show(); }

						if(typeof(eps_update_autofills__RAND__) == 'function') eps_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_eps__RAND__.value, t: 'oportunidad', f: 'eps' },
				success: function(resp) {
					$j('[id=eps-container__RAND__], [id=eps-container-readonly__RAND__]').html('<span id="eps-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=eps_view_parent]').hide(); } else { $j('.btn[id=eps_view_parent]').show(); }

					if(typeof(eps_update_autofills__RAND__) == 'function') eps_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/oportunidad_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/oportunidad_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Oportunidad details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert) {
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return oportunidad_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return oportunidad_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id) {
		if(!$_REQUEST['Embedded']) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate) {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return oportunidad_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		} else {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3) { // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		} else {
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)) {
		$jsReadOnly = '';
		$jsReadOnly .= "\tjQuery('#tipodoc').replaceWith('<div class=\"form-control-static\" id=\"tipodoc\">' + (jQuery('#tipodoc').val() || '') + '</div>'); jQuery('#tipodoc-multi-selection-help').hide();\n";
		$jsReadOnly .= "\tjQuery('#doc').replaceWith('<div class=\"form-control-static\" id=\"doc\">' + (jQuery('#doc').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#nombres').replaceWith('<div class=\"form-control-static\" id=\"nombres\">' + (jQuery('#nombres').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#apellidos').replaceWith('<div class=\"form-control-static\" id=\"apellidos\">' + (jQuery('#apellidos').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#regimen').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#regimen_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#eps').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#eps_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#fechanac').prop('readonly', true);\n";
		$jsReadOnly .= "\tjQuery('#fechanacDay, #fechanacMonth, #fechanacYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#edad').replaceWith('<div class=\"form-control-static\" id=\"edad\">' + (jQuery('#edad').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#atencionreq').replaceWith('<div class=\"form-control-static\" id=\"atencionreq\">' + (jQuery('#atencionreq').val() || '') + '</div>'); jQuery('#atencionreq-multi-selection-help').hide();\n";
		$jsReadOnly .= "\tjQuery('#fechaorden').prop('readonly', true);\n";
		$jsReadOnly .= "\tjQuery('#fechaordenDay, #fechaordenMonth, #fechaordenYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#fechacita').prop('readonly', true);\n";
		$jsReadOnly .= "\tjQuery('#fechacitaDay, #fechacitaMonth, #fechacitaYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#calificacion').replaceWith('<div class=\"form-control-static\" id=\"calificacion\">' + (jQuery('#calificacion').val() || '') + '</div>'); jQuery('#calificacion-multi-selection-help').hide();\n";
		$jsReadOnly .= "\tjQuery('#observaciones').replaceWith('<div class=\"form-control-static\" id=\"observaciones\">' + (jQuery('#observaciones').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	} elseif($AllowInsert) {
		$jsEditable = "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(tipodoc)%%>', $combo_tipodoc->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(tipodoc)%%>', $combo_tipodoc->SelectedData, $templateCode);
	$templateCode = str_replace('<%%COMBO(regimen)%%>', $combo_regimen->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(regimen)%%>', $combo_regimen->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(regimen)%%>', urlencode($combo_regimen->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(eps)%%>', $combo_eps->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(eps)%%>', $combo_eps->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(eps)%%>', urlencode($combo_eps->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(fechanac)%%>', ($selected_id && !$arrPerm[3] ? '<div class="form-control-static">' . $combo_fechanac->GetHTML(true) . '</div>' : $combo_fechanac->GetHTML()), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(fechanac)%%>', $combo_fechanac->GetHTML(true), $templateCode);
	$templateCode = str_replace('<%%COMBO(atencionreq)%%>', $combo_atencionreq->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(atencionreq)%%>', $combo_atencionreq->SelectedData, $templateCode);
	$templateCode = str_replace('<%%COMBO(fechaorden)%%>', ($selected_id && !$arrPerm[3] ? '<div class="form-control-static">' . $combo_fechaorden->GetHTML(true) . '</div>' : $combo_fechaorden->GetHTML()), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(fechaorden)%%>', $combo_fechaorden->GetHTML(true), $templateCode);
	$templateCode = str_replace('<%%COMBO(fechacita)%%>', ($selected_id && !$arrPerm[3] ? '<div class="form-control-static">' . $combo_fechacita->GetHTML(true) . '</div>' : $combo_fechacita->GetHTML()), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(fechacita)%%>', $combo_fechacita->GetHTML(true), $templateCode);
	$templateCode = str_replace('<%%COMBO(calificacion)%%>', $combo_calificacion->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(calificacion)%%>', $combo_calificacion->SelectedData, $templateCode);

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array('regimen' => array('regimenes', 'Regimen'), 'eps' => array('eps', 'Eps'), );
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !$_REQUEST['Embedded']*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(tipodoc)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(doc)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(nombres)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(apellidos)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(regimen)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(eps)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(fechanac)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(edad)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(atencionreq)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(fechaorden)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(fechacita)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(calificacion)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(observaciones)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(asignado)%%>', '', $templateCode);

	// process values
	if($selected_id) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(tipodoc)%%>', safe_html($urow['tipodoc']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(tipodoc)%%>', html_attr($row['tipodoc']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(tipodoc)%%>', urlencode($urow['tipodoc']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(doc)%%>', safe_html($urow['doc']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(doc)%%>', html_attr($row['doc']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(doc)%%>', urlencode($urow['doc']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(nombres)%%>', safe_html($urow['nombres']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(nombres)%%>', html_attr($row['nombres']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(nombres)%%>', urlencode($urow['nombres']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(apellidos)%%>', safe_html($urow['apellidos']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(apellidos)%%>', html_attr($row['apellidos']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(apellidos)%%>', urlencode($urow['apellidos']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(regimen)%%>', safe_html($urow['regimen']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(regimen)%%>', html_attr($row['regimen']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(regimen)%%>', urlencode($urow['regimen']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(eps)%%>', safe_html($urow['eps']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(eps)%%>', html_attr($row['eps']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(eps)%%>', urlencode($urow['eps']), $templateCode);
		$templateCode = str_replace('<%%VALUE(fechanac)%%>', @date('d/m/Y', @strtotime(html_attr($row['fechanac']))), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fechanac)%%>', urlencode(@date('d/m/Y', @strtotime(html_attr($urow['fechanac'])))), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(edad)%%>', safe_html($urow['edad']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(edad)%%>', html_attr($row['edad']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(edad)%%>', urlencode($urow['edad']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(atencionreq)%%>', safe_html($urow['atencionreq']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(atencionreq)%%>', html_attr($row['atencionreq']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(atencionreq)%%>', urlencode($urow['atencionreq']), $templateCode);
		$templateCode = str_replace('<%%VALUE(fechaorden)%%>', @date('d/m/Y', @strtotime(html_attr($row['fechaorden']))), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fechaorden)%%>', urlencode(@date('d/m/Y', @strtotime(html_attr($urow['fechaorden'])))), $templateCode);
		$templateCode = str_replace('<%%VALUE(fechacita)%%>', @date('d/m/Y', @strtotime(html_attr($row['fechacita']))), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fechacita)%%>', urlencode(@date('d/m/Y', @strtotime(html_attr($urow['fechacita'])))), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(calificacion)%%>', safe_html($urow['calificacion']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(calificacion)%%>', html_attr($row['calificacion']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(calificacion)%%>', urlencode($urow['calificacion']), $templateCode);
		if($dvprint || (!$AllowUpdate && !$AllowInsert)) {
			$templateCode = str_replace('<%%VALUE(observaciones)%%>', safe_html($urow['observaciones']), $templateCode);
		} else {
			$templateCode = str_replace('<%%VALUE(observaciones)%%>', safe_html($urow['observaciones'], true), $templateCode);
		}
		$templateCode = str_replace('<%%URLVALUE(observaciones)%%>', urlencode($urow['observaciones']), $templateCode);
		$templateCode = str_replace('<%%VALUE(asignado)%%>', safe_html($urow['asignado']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(asignado)%%>', urlencode($urow['asignado']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(tipodoc)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(tipodoc)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(doc)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(doc)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(nombres)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(nombres)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(apellidos)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(apellidos)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(regimen)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(regimen)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(eps)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(eps)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(fechanac)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fechanac)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(edad)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(edad)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(atencionreq)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(atencionreq)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(fechaorden)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fechaorden)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(fechacita)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fechacita)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(calificacion)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(calificacion)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(observaciones)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(observaciones)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(asignado)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(asignado)%%>', urlencode(''), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('oportunidad');
	if($selected_id) {
		$jdata = get_joined_record('oportunidad', $selected_id);
		if($jdata === false) $jdata = get_defaults('oportunidad');
		$rdata = $row;
	}
	$templateCode .= loadView('oportunidad-ajax-cache', array('rdata' => $rdata, 'jdata' => $jdata));

	// hook: oportunidad_dv
	if(function_exists('oportunidad_dv')) {
		$args=[];
		oportunidad_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}