<?php
// This script and data application were generated by AppGini 5.97
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir = dirname(__FILE__);
	include_once("$currDir/lib.php");

	handle_maintenance();

	header('Content-type: text/javascript; charset=' . datalist_db_encoding);

	$table_perms = getTablePermissions('pqr');
	if(!$table_perms['access']) die('// Access denied!');

	$mfk = $_GET['mfk'];
	$id = makeSafe($_GET['id']);
	$rnd1 = intval($_GET['rnd1']); if(!$rnd1) $rnd1 = '';

	if(!$mfk) {
		die('// No js code available!');
	}

	switch($mfk) {

		case 'eps':
			if(!$id) {
				?>
				$j('#gerente<?php echo $rnd1; ?>').html('&nbsp;');
				$j('#teleps<?php echo $rnd1; ?>').html('&nbsp;');
				$j('#maileps<?php echo $rnd1; ?>').html('&nbsp;');
				<?php
				break;
			}
			$res = sql("SELECT `eps`.`razonsocial` as 'razonsocial', IF(    CHAR_LENGTH(`regimenes1`.`nombre`), CONCAT_WS('',   `regimenes1`.`nombre`), '') as 'regimen', `eps`.`gerente` as 'gerente', `eps`.`telefono` as 'telefono', `eps`.`correo` as 'correo', `eps`.`correo2` as 'correo2', `eps`.`correo3` as 'correo3' FROM `eps` LEFT JOIN `regimenes` as regimenes1 ON `regimenes1`.`nombre`=`eps`.`regimen`  WHERE `eps`.`razonsocial`='{$id}' limit 1", $eo);
			$row = db_fetch_assoc($res);
			?>
			$j('#gerente<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(array("\r", "\n"), '', nl2br($row['gerente']))); ?>&nbsp;');
			$j('#teleps<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(array("\r", "\n"), '', nl2br($row['telefono']))); ?>&nbsp;');
			$j('#maileps<?php echo $rnd1; ?>').html('<?php echo addslashes(str_replace(array("\r", "\n"), '', nl2br($row['correo']))); ?>&nbsp;');
			<?php
			break;


	}

?>