<?php

// Data functions (insert, update, delete, form) for table prass

// This script and data application were generated by AppGini 5.97
// Download AppGini for free from https://bigprof.com/appgini/download/

function prass_insert(&$error_message = '') {
	global $Translation;

	// mm: can member insert record?
	$arrPerm = getTablePermissions('prass');
	if(!$arrPerm['insert']) return false;

	$data = [
		'documento' => Request::val('documento', ''),
		'nombrepaciente' => Request::val('nombrepaciente', ''),
		'regimen' => Request::lookup('regimen', ''),
		'eps' => Request::lookup('eps', ''),
		'direccion' => Request::val('direccion', ''),
		'telefono' => Request::val('telefono', ''),
		'consulta' => Request::val('consulta', ''),
		'fechaconsulta' => Request::dateComponents('fechaconsulta', ''),
		'prueba' => Request::val('prueba', ''),
		'fechaprueba' => Request::dateComponents('fechaprueba', ''),
		'estado' => Request::val('estado', ''),
		'observacion' => br2nl(Request::val('observacion', '')),
	];

	if($data['nombrepaciente'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Nombre del usuario': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['eps'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Eps': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['direccion'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Direccion': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['telefono'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Telefono': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['consulta'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Recibi&#243; Consulta para atenci&#243;n por sospecha o contagio del COVID?': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['prueba'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Se realiz&#243; prueba confirmatoria para el COVID?': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['estado'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Estado': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}

	// hook: prass_before_insert
	if(function_exists('prass_before_insert')) {
		$args = [];
		if(!prass_before_insert($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$error = '';
	// set empty fields to NULL
	$data = array_map(function($v) { return ($v === '' ? NULL : $v); }, $data);
	insert('prass', backtick_keys_once($data), $error);
	if($error)
		die("{$error}<br><a href=\"#\" onclick=\"history.go(-1);\">{$Translation['< back']}</a>");

	$recID = db_insert_id(db_link());

	update_calc_fields('prass', $recID, calculated_fields()['prass']);

	// hook: prass_after_insert
	if(function_exists('prass_after_insert')) {
		$res = sql("SELECT * FROM `prass` WHERE `id`='" . makeSafe($recID, false) . "' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) {
			$data = array_map('makeSafe', $row);
		}
		$data['selectedID'] = makeSafe($recID, false);
		$args=[];
		if(!prass_after_insert($data, getMemberInfo(), $args)) { return $recID; }
	}

	// mm: save ownership data
	set_record_owner('prass', $recID, getLoggedMemberID());

	// if this record is a copy of another record, copy children if applicable
	if(!empty($_REQUEST['SelectedID'])) prass_copy_children($recID, $_REQUEST['SelectedID']);

	return $recID;
}

function prass_copy_children($destination_id, $source_id) {
	global $Translation;
	$requests = []; // array of curl handlers for launching insert requests
	$eo = ['silentErrors' => true];
	$safe_sid = makeSafe($source_id);

	// launch requests, asynchronously
	curl_batch($requests);
}

function prass_delete($selected_id, $AllowDeleteOfParents = false, $skipChecks = false) {
	// insure referential integrity ...
	global $Translation;
	$selected_id = makeSafe($selected_id);

	// mm: can member delete record?
	if(!check_record_permission('prass', $selected_id, 'delete')) {
		return $Translation['You don\'t have enough permissions to delete this record'];
	}

	// hook: prass_before_delete
	if(function_exists('prass_before_delete')) {
		$args = [];
		if(!prass_before_delete($selected_id, $skipChecks, getMemberInfo(), $args))
			return $Translation['Couldn\'t delete this record'] . (
				!empty($args['error_message']) ?
					'<div class="text-bold">' . strip_tags($args['error_message']) . '</div>'
					: '' 
			);
	}

	sql("DELETE FROM `prass` WHERE `id`='{$selected_id}'", $eo);

	// hook: prass_after_delete
	if(function_exists('prass_after_delete')) {
		$args = [];
		prass_after_delete($selected_id, getMemberInfo(), $args);
	}

	// mm: delete ownership data
	sql("DELETE FROM `membership_userrecords` WHERE `tableName`='prass' AND `pkValue`='{$selected_id}'", $eo);
}

function prass_update(&$selected_id, &$error_message = '') {
	global $Translation;

	// mm: can member edit record?
	if(!check_record_permission('prass', $selected_id, 'edit')) return false;

	$data = [
		'fecha' => parseCode('<%%editingDate%%>', false, true),
		'documento' => Request::val('documento', ''),
		'nombrepaciente' => Request::val('nombrepaciente', ''),
		'regimen' => Request::lookup('regimen', ''),
		'eps' => Request::lookup('eps', ''),
		'direccion' => Request::val('direccion', ''),
		'telefono' => Request::val('telefono', ''),
		'consulta' => Request::val('consulta', ''),
		'fechaconsulta' => Request::dateComponents('fechaconsulta', ''),
		'prueba' => Request::val('prueba', ''),
		'fechaprueba' => Request::dateComponents('fechaprueba', ''),
		'estado' => Request::val('estado', ''),
		'observacion' => br2nl(Request::val('observacion', '')),
	];

	if($data['nombrepaciente'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Nombre del usuario': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['eps'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Eps': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['direccion'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Direccion': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['telefono'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Telefono': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['consulta'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Recibi&#243; Consulta para atenci&#243;n por sospecha o contagio del COVID?': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['prueba'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Se realiz&#243; prueba confirmatoria para el COVID?': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	if($data['estado'] === '') {
		echo StyleSheet() . "\n\n<div class=\"alert alert-danger\">{$Translation['error:']} 'Estado': {$Translation['field not null']}<br><br>";
		echo '<a href="" onclick="history.go(-1); return false;">' . $Translation['< back'] . '</a></div>';
		exit;
	}
	// get existing values
	$old_data = getRecord('prass', $selected_id);
	if(is_array($old_data)) {
		$old_data = array_map('makeSafe', $old_data);
		$old_data['selectedID'] = makeSafe($selected_id);
	}

	$data['selectedID'] = makeSafe($selected_id);

	// hook: prass_before_update
	if(function_exists('prass_before_update')) {
		$args = ['old_data' => $old_data];
		if(!prass_before_update($data, getMemberInfo(), $args)) {
			if(isset($args['error_message'])) $error_message = $args['error_message'];
			return false;
		}
	}

	$set = $data; unset($set['selectedID']);
	foreach ($set as $field => $value) {
		$set[$field] = ($value !== '' && $value !== NULL) ? $value : NULL;
	}

	if(!update(
		'prass', 
		backtick_keys_once($set), 
		['`id`' => $selected_id], 
		$error_message
	)) {
		echo $error_message;
		echo '<a href="prass_view.php?SelectedID=' . urlencode($selected_id) . "\">{$Translation['< back']}</a>";
		exit;
	}


	$eo = ['silentErrors' => true];

	update_calc_fields('prass', $data['selectedID'], calculated_fields()['prass']);

	// hook: prass_after_update
	if(function_exists('prass_after_update')) {
		$res = sql("SELECT * FROM `prass` WHERE `id`='{$data['selectedID']}' LIMIT 1", $eo);
		if($row = db_fetch_assoc($res)) $data = array_map('makeSafe', $row);

		$data['selectedID'] = $data['id'];
		$args = ['old_data' => $old_data];
		if(!prass_after_update($data, getMemberInfo(), $args)) return;
	}

	// mm: update ownership data
	sql("UPDATE `membership_userrecords` SET `dateUpdated`='" . time() . "' WHERE `tableName`='prass' AND `pkValue`='" . makeSafe($selected_id) . "'", $eo);
}

function prass_form($selected_id = '', $AllowUpdate = 1, $AllowInsert = 1, $AllowDelete = 1, $ShowCancel = 0, $TemplateDV = '', $TemplateDVP = '') {
	// function to return an editable form for a table records
	// and fill it with data of record whose ID is $selected_id. If $selected_id
	// is empty, an empty form is shown, with only an 'Add New'
	// button displayed.

	global $Translation;

	// mm: get table permissions
	$arrPerm = getTablePermissions('prass');
	if(!$arrPerm['insert'] && $selected_id=='') return $Translation['tableAccessDenied'];
	$AllowInsert = ($arrPerm['insert'] ? true : false);
	// print preview?
	$dvprint = false;
	if($selected_id && $_REQUEST['dvprint_x'] != '') {
		$dvprint = true;
	}

	$filterer_regimen = thisOr($_REQUEST['filterer_regimen'], '');
	$filterer_eps = thisOr($_REQUEST['filterer_eps'], '');

	// populate filterers, starting from children to grand-parents
	if($filterer_eps && !$filterer_regimen) $filterer_regimen = sqlValue("select regimen from eps where razonsocial='" . makeSafe($filterer_eps) . "'");

	// unique random identifier
	$rnd1 = ($dvprint ? rand(1000000, 9999999) : '');
	// combobox: fecha
	$combo_fecha = new DateCombo;
	$combo_fecha->DateFormat = "dmy";
	$combo_fecha->MinYear = 1900;
	$combo_fecha->MaxYear = 2100;
	$combo_fecha->DefaultDate = parseMySQLDate('<%%editingDate%%>', '<%%editingDate%%>');
	$combo_fecha->MonthNames = $Translation['month names'];
	$combo_fecha->NamePrefix = 'fecha';
	// combobox: regimen
	$combo_regimen = new DataCombo;
	// combobox: eps, filterable by: regimen
	$combo_eps = new DataCombo;
	// combobox: consulta
	$combo_consulta = new Combo;
	$combo_consulta->ListType = 0;
	$combo_consulta->MultipleSeparator = ', ';
	$combo_consulta->ListBoxHeight = 10;
	$combo_consulta->RadiosPerLine = 1;
	if(is_file(dirname(__FILE__).'/hooks/prass.consulta.csv')) {
		$consulta_data = addslashes(implode('', @file(dirname(__FILE__).'/hooks/prass.consulta.csv')));
		$combo_consulta->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions($consulta_data)));
		$combo_consulta->ListData = $combo_consulta->ListItem;
	} else {
		$combo_consulta->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions(";;SI;;NO")));
		$combo_consulta->ListData = $combo_consulta->ListItem;
	}
	$combo_consulta->SelectName = 'consulta';
	$combo_consulta->AllowNull = false;
	// combobox: fechaconsulta
	$combo_fechaconsulta = new DateCombo;
	$combo_fechaconsulta->DateFormat = "dmy";
	$combo_fechaconsulta->MinYear = 1900;
	$combo_fechaconsulta->MaxYear = 2100;
	$combo_fechaconsulta->DefaultDate = parseMySQLDate('', '');
	$combo_fechaconsulta->MonthNames = $Translation['month names'];
	$combo_fechaconsulta->NamePrefix = 'fechaconsulta';
	// combobox: prueba
	$combo_prueba = new Combo;
	$combo_prueba->ListType = 0;
	$combo_prueba->MultipleSeparator = ', ';
	$combo_prueba->ListBoxHeight = 10;
	$combo_prueba->RadiosPerLine = 1;
	if(is_file(dirname(__FILE__).'/hooks/prass.prueba.csv')) {
		$prueba_data = addslashes(implode('', @file(dirname(__FILE__).'/hooks/prass.prueba.csv')));
		$combo_prueba->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions($prueba_data)));
		$combo_prueba->ListData = $combo_prueba->ListItem;
	} else {
		$combo_prueba->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions(";;SI;;NO")));
		$combo_prueba->ListData = $combo_prueba->ListItem;
	}
	$combo_prueba->SelectName = 'prueba';
	$combo_prueba->AllowNull = false;
	// combobox: fechaprueba
	$combo_fechaprueba = new DateCombo;
	$combo_fechaprueba->DateFormat = "dmy";
	$combo_fechaprueba->MinYear = 1900;
	$combo_fechaprueba->MaxYear = 2100;
	$combo_fechaprueba->DefaultDate = parseMySQLDate('', '');
	$combo_fechaprueba->MonthNames = $Translation['month names'];
	$combo_fechaprueba->NamePrefix = 'fechaprueba';
	// combobox: estado
	$combo_estado = new Combo;
	$combo_estado->ListType = 0;
	$combo_estado->MultipleSeparator = ', ';
	$combo_estado->ListBoxHeight = 10;
	$combo_estado->RadiosPerLine = 1;
	if(is_file(dirname(__FILE__).'/hooks/prass.estado.csv')) {
		$estado_data = addslashes(implode('', @file(dirname(__FILE__).'/hooks/prass.estado.csv')));
		$combo_estado->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions($estado_data)));
		$combo_estado->ListData = $combo_estado->ListItem;
	} else {
		$combo_estado->ListItem = explode('||', entitiesToUTF8(convertLegacyOptions("Contactado")));
		$combo_estado->ListData = $combo_estado->ListItem;
	}
	$combo_estado->SelectName = 'estado';
	$combo_estado->AllowNull = false;

	if($selected_id) {
		// mm: check member permissions
		if(!$arrPerm['view']) return $Translation['tableAccessDenied'];

		// mm: who is the owner?
		$ownerGroupID = sqlValue("SELECT `groupID` FROM `membership_userrecords` WHERE `tableName`='prass' AND `pkValue`='" . makeSafe($selected_id) . "'");
		$ownerMemberID = sqlValue("SELECT LCASE(`memberID`) FROM `membership_userrecords` WHERE `tableName`='prass' AND `pkValue`='" . makeSafe($selected_id) . "'");

		if($arrPerm['view'] == 1 && getLoggedMemberID() != $ownerMemberID) return $Translation['tableAccessDenied'];
		if($arrPerm['view'] == 2 && getLoggedGroupID() != $ownerGroupID) return $Translation['tableAccessDenied'];

		// can edit?
		$AllowUpdate = 0;
		if(($arrPerm['edit'] == 1 && $ownerMemberID == getLoggedMemberID()) || ($arrPerm['edit'] == 2 && $ownerGroupID == getLoggedGroupID()) || $arrPerm['edit'] == 3) {
			$AllowUpdate = 1;
		}

		$res = sql("SELECT * FROM `prass` WHERE `id`='" . makeSafe($selected_id) . "'", $eo);
		if(!($row = db_fetch_array($res))) {
			return error_message($Translation['No records found'], 'prass_view.php', false);
		}
		$combo_fecha->DefaultDate = $row['fecha'];
		$combo_regimen->SelectedData = $row['regimen'];
		$combo_eps->SelectedData = $row['eps'];
		$combo_consulta->SelectedData = $row['consulta'];
		$combo_fechaconsulta->DefaultDate = $row['fechaconsulta'];
		$combo_prueba->SelectedData = $row['prueba'];
		$combo_fechaprueba->DefaultDate = $row['fechaprueba'];
		$combo_estado->SelectedData = $row['estado'];
		$urow = $row; /* unsanitized data */
		$row = array_map('safe_html', $row);
	} else {
		$combo_regimen->SelectedData = $filterer_regimen;
		$combo_eps->SelectedData = $filterer_eps;
		$combo_consulta->SelectedText = ( $_REQUEST['FilterField'][1] == '9' && $_REQUEST['FilterOperator'][1] == '<=>' ? $_REQUEST['FilterValue'][1] : '');
		$combo_prueba->SelectedText = ( $_REQUEST['FilterField'][1] == '11' && $_REQUEST['FilterOperator'][1] == '<=>' ? $_REQUEST['FilterValue'][1] : '');
		$combo_estado->SelectedText = ( $_REQUEST['FilterField'][1] == '13' && $_REQUEST['FilterOperator'][1] == '<=>' ? $_REQUEST['FilterValue'][1] : '');
	}
	$combo_regimen->HTML = '<span id="regimen-container' . $rnd1 . '"></span><input type="hidden" name="regimen" id="regimen' . $rnd1 . '" value="' . html_attr($combo_regimen->SelectedData) . '">';
	$combo_regimen->MatchText = '<span id="regimen-container-readonly' . $rnd1 . '"></span><input type="hidden" name="regimen" id="regimen' . $rnd1 . '" value="' . html_attr($combo_regimen->SelectedData) . '">';
	$combo_eps->HTML = '<span id="eps-container' . $rnd1 . '"></span><input type="hidden" name="eps" id="eps' . $rnd1 . '" value="' . html_attr($combo_eps->SelectedData) . '">';
	$combo_eps->MatchText = '<span id="eps-container-readonly' . $rnd1 . '"></span><input type="hidden" name="eps" id="eps' . $rnd1 . '" value="' . html_attr($combo_eps->SelectedData) . '">';
	$combo_consulta->Render();
	$combo_prueba->Render();
	$combo_estado->Render();

	ob_start();
	?>

	<script>
		// initial lookup values
		AppGini.current_regimen__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['regimen'] : htmlspecialchars($filterer_regimen, ENT_QUOTES)); ?>"};
		AppGini.current_eps__RAND__ = { text: "", value: "<?php echo addslashes($selected_id ? $urow['eps'] : htmlspecialchars($filterer_eps, ENT_QUOTES)); ?>"};

		jQuery(function() {
			setTimeout(function() {
				if(typeof(regimen_reload__RAND__) == 'function') regimen_reload__RAND__();
				<?php echo (!$AllowUpdate || $dvprint ? 'if(typeof(eps_reload__RAND__) == \'function\') eps_reload__RAND__(AppGini.current_regimen__RAND__.value);' : ''); ?>
			}, 50); /* we need to slightly delay client-side execution of the above code to allow AppGini.ajaxCache to work */
		});
		function regimen_reload__RAND__() {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#regimen-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { id: AppGini.current_regimen__RAND__.value, t: 'prass', f: 'regimen' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="regimen"]').val(resp.results[0].id);
							$j('[id=regimen-container-readonly__RAND__]').html('<span id="regimen-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=regimenes_view_parent]').hide(); } else { $j('.btn[id=regimenes_view_parent]').show(); }

						if(typeof(eps_reload__RAND__) == 'function') eps_reload__RAND__(AppGini.current_regimen__RAND__.value);

							if(typeof(regimen_update_autofills__RAND__) == 'function') regimen_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { s: term, p: page, t: 'prass', f: 'regimen' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_regimen__RAND__.value = e.added.id;
				AppGini.current_regimen__RAND__.text = e.added.text;
				$j('[name="regimen"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=regimenes_view_parent]').hide(); } else { $j('.btn[id=regimenes_view_parent]').show(); }

						if(typeof(eps_reload__RAND__) == 'function') eps_reload__RAND__(AppGini.current_regimen__RAND__.value);

				if(typeof(regimen_update_autofills__RAND__) == 'function') regimen_update_autofills__RAND__();
			});

			if(!$j("#regimen-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_regimen__RAND__.value, t: 'prass', f: 'regimen' },
					success: function(resp) {
						$j('[name="regimen"]').val(resp.results[0].id);
						$j('[id=regimen-container-readonly__RAND__]').html('<span id="regimen-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=regimenes_view_parent]').hide(); } else { $j('.btn[id=regimenes_view_parent]').show(); }

						if(typeof(regimen_update_autofills__RAND__) == 'function') regimen_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_regimen__RAND__.value, t: 'prass', f: 'regimen' },
				success: function(resp) {
					$j('[id=regimen-container__RAND__], [id=regimen-container-readonly__RAND__]').html('<span id="regimen-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=regimenes_view_parent]').hide(); } else { $j('.btn[id=regimenes_view_parent]').show(); }

					if(typeof(regimen_update_autofills__RAND__) == 'function') regimen_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
		function eps_reload__RAND__(filterer_regimen) {
		<?php if(($AllowUpdate || $AllowInsert) && !$dvprint) { ?>

			$j("#eps-container__RAND__").select2({
				/* initial default value */
				initSelection: function(e, c) {
					$j.ajax({
						url: 'ajax_combo.php',
						dataType: 'json',
						data: { filterer_regimen: filterer_regimen, id: AppGini.current_eps__RAND__.value, t: 'prass', f: 'eps' },
						success: function(resp) {
							c({
								id: resp.results[0].id,
								text: resp.results[0].text
							});
							$j('[name="eps"]').val(resp.results[0].id);
							$j('[id=eps-container-readonly__RAND__]').html('<span id="eps-match-text">' + resp.results[0].text + '</span>');
							if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=eps_view_parent]').hide(); } else { $j('.btn[id=eps_view_parent]').show(); }


							if(typeof(eps_update_autofills__RAND__) == 'function') eps_update_autofills__RAND__();
						}
					});
				},
				width: '100%',
				formatNoMatches: function(term) { return '<?php echo addslashes($Translation['No matches found!']); ?>'; },
				minimumResultsForSearch: 5,
				loadMorePadding: 200,
				ajax: {
					url: 'ajax_combo.php',
					dataType: 'json',
					cache: true,
					data: function(term, page) { return { filterer_regimen: filterer_regimen, s: term, p: page, t: 'prass', f: 'eps' }; },
					results: function(resp, page) { return resp; }
				},
				escapeMarkup: function(str) { return str; }
			}).on('change', function(e) {
				AppGini.current_eps__RAND__.value = e.added.id;
				AppGini.current_eps__RAND__.text = e.added.text;
				$j('[name="eps"]').val(e.added.id);
				if(e.added.id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=eps_view_parent]').hide(); } else { $j('.btn[id=eps_view_parent]').show(); }


				if(typeof(eps_update_autofills__RAND__) == 'function') eps_update_autofills__RAND__();
			});

			if(!$j("#eps-container__RAND__").length) {
				$j.ajax({
					url: 'ajax_combo.php',
					dataType: 'json',
					data: { id: AppGini.current_eps__RAND__.value, t: 'prass', f: 'eps' },
					success: function(resp) {
						$j('[name="eps"]').val(resp.results[0].id);
						$j('[id=eps-container-readonly__RAND__]').html('<span id="eps-match-text">' + resp.results[0].text + '</span>');
						if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=eps_view_parent]').hide(); } else { $j('.btn[id=eps_view_parent]').show(); }

						if(typeof(eps_update_autofills__RAND__) == 'function') eps_update_autofills__RAND__();
					}
				});
			}

		<?php } else { ?>

			$j.ajax({
				url: 'ajax_combo.php',
				dataType: 'json',
				data: { id: AppGini.current_eps__RAND__.value, t: 'prass', f: 'eps' },
				success: function(resp) {
					$j('[id=eps-container__RAND__], [id=eps-container-readonly__RAND__]').html('<span id="eps-match-text">' + resp.results[0].text + '</span>');
					if(resp.results[0].id == '<?php echo empty_lookup_value; ?>') { $j('.btn[id=eps_view_parent]').hide(); } else { $j('.btn[id=eps_view_parent]').show(); }

					if(typeof(eps_update_autofills__RAND__) == 'function') eps_update_autofills__RAND__();
				}
			});
		<?php } ?>

		}
	</script>
	<?php

	$lookups = str_replace('__RAND__', $rnd1, ob_get_contents());
	ob_end_clean();


	// code for template based detail view forms

	// open the detail view template
	if($dvprint) {
		$template_file = is_file("./{$TemplateDVP}") ? "./{$TemplateDVP}" : './templates/prass_templateDVP.html';
		$templateCode = @file_get_contents($template_file);
	} else {
		$template_file = is_file("./{$TemplateDV}") ? "./{$TemplateDV}" : './templates/prass_templateDV.html';
		$templateCode = @file_get_contents($template_file);
	}

	// process form title
	$templateCode = str_replace('<%%DETAIL_VIEW_TITLE%%>', 'Pras details', $templateCode);
	$templateCode = str_replace('<%%RND1%%>', $rnd1, $templateCode);
	$templateCode = str_replace('<%%EMBEDDED%%>', ($_REQUEST['Embedded'] ? 'Embedded=1' : ''), $templateCode);
	// process buttons
	if($AllowInsert) {
		if(!$selected_id) $templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-success" id="insert" name="insert_x" value="1" onclick="return prass_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save New'] . '</button>', $templateCode);
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="insert" name="insert_x" value="1" onclick="return prass_validateData();"><i class="glyphicon glyphicon-plus-sign"></i> ' . $Translation['Save As Copy'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%INSERT_BUTTON%%>', '', $templateCode);
	}

	// 'Back' button action
	if($_REQUEST['Embedded']) {
		$backAction = 'AppGini.closeParentModal(); return false;';
	} else {
		$backAction = '$j(\'form\').eq(0).attr(\'novalidate\', \'novalidate\'); document.myform.reset(); return true;';
	}

	if($selected_id) {
		if(!$_REQUEST['Embedded']) $templateCode = str_replace('<%%DVPRINT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="dvprint" name="dvprint_x" value="1" onclick="$j(\'form\').eq(0).prop(\'novalidate\', true); document.myform.reset(); return true;" title="' . html_attr($Translation['Print Preview']) . '"><i class="glyphicon glyphicon-print"></i> ' . $Translation['Print Preview'] . '</button>', $templateCode);
		if($AllowUpdate) {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '<button type="submit" class="btn btn-success btn-lg" id="update" name="update_x" value="1" onclick="return prass_validateData();" title="' . html_attr($Translation['Save Changes']) . '"><i class="glyphicon glyphicon-ok"></i> ' . $Translation['Save Changes'] . '</button>', $templateCode);
		} else {
			$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		}
		if(($arrPerm[4]==1 && $ownerMemberID==getLoggedMemberID()) || ($arrPerm[4]==2 && $ownerGroupID==getLoggedGroupID()) || $arrPerm[4]==3) { // allow delete?
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '<button type="submit" class="btn btn-danger" id="delete" name="delete_x" value="1" onclick="return confirm(\'' . $Translation['are you sure?'] . '\');" title="' . html_attr($Translation['Delete']) . '"><i class="glyphicon glyphicon-trash"></i> ' . $Translation['Delete'] . '</button>', $templateCode);
		} else {
			$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		}
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>', $templateCode);
	} else {
		$templateCode = str_replace('<%%UPDATE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DELETE_BUTTON%%>', '', $templateCode);
		$templateCode = str_replace('<%%DESELECT_BUTTON%%>', ($ShowCancel ? '<button type="submit" class="btn btn-default" id="deselect" name="deselect_x" value="1" onclick="' . $backAction . '" title="' . html_attr($Translation['Back']) . '"><i class="glyphicon glyphicon-chevron-left"></i> ' . $Translation['Back'] . '</button>' : ''), $templateCode);
	}

	// set records to read only if user can't insert new records and can't edit current record
	if(($selected_id && !$AllowUpdate && !$AllowInsert) || (!$selected_id && !$AllowInsert)) {
		$jsReadOnly = '';
		$jsReadOnly .= "\tjQuery('#documento').replaceWith('<div class=\"form-control-static\" id=\"documento\">' + (jQuery('#documento').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#nombrepaciente').replaceWith('<div class=\"form-control-static\" id=\"nombrepaciente\">' + (jQuery('#nombrepaciente').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#regimen').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#regimen_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#eps').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#eps_caption').prop('disabled', true).css({ color: '#555', backgroundColor: 'white' });\n";
		$jsReadOnly .= "\tjQuery('#direccion').replaceWith('<div class=\"form-control-static\" id=\"direccion\">' + (jQuery('#direccion').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#telefono').replaceWith('<div class=\"form-control-static\" id=\"telefono\">' + (jQuery('#telefono').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('#consulta').replaceWith('<div class=\"form-control-static\" id=\"consulta\">' + (jQuery('#consulta').val() || '') + '</div>'); jQuery('#consulta-multi-selection-help').hide();\n";
		$jsReadOnly .= "\tjQuery('#fechaconsulta').prop('readonly', true);\n";
		$jsReadOnly .= "\tjQuery('#fechaconsultaDay, #fechaconsultaMonth, #fechaconsultaYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#prueba').replaceWith('<div class=\"form-control-static\" id=\"prueba\">' + (jQuery('#prueba').val() || '') + '</div>'); jQuery('#prueba-multi-selection-help').hide();\n";
		$jsReadOnly .= "\tjQuery('#fechaprueba').prop('readonly', true);\n";
		$jsReadOnly .= "\tjQuery('#fechapruebaDay, #fechapruebaMonth, #fechapruebaYear').prop('disabled', true).css({ color: '#555', backgroundColor: '#fff' });\n";
		$jsReadOnly .= "\tjQuery('#estado').replaceWith('<div class=\"form-control-static\" id=\"estado\">' + (jQuery('#estado').val() || '') + '</div>'); jQuery('#estado-multi-selection-help').hide();\n";
		$jsReadOnly .= "\tjQuery('#observacion').replaceWith('<div class=\"form-control-static\" id=\"observacion\">' + (jQuery('#observacion').val() || '') + '</div>');\n";
		$jsReadOnly .= "\tjQuery('.select2-container').hide();\n";

		$noUploads = true;
	} elseif($AllowInsert) {
		$jsEditable = "\tjQuery('form').eq(0).data('already_changed', true);"; // temporarily disable form change handler
		$jsEditable .= "\tjQuery('form').eq(0).data('already_changed', false);"; // re-enable form change handler
	}

	// process combos
	$templateCode = str_replace('<%%COMBO(fecha)%%>', ($selected_id && !$arrPerm[3] ? '<div class="form-control-static">' . $combo_fecha->GetHTML(true) . '</div>' : $combo_fecha->GetHTML()), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(fecha)%%>', $combo_fecha->GetHTML(true), $templateCode);
	$templateCode = str_replace('<%%COMBO(regimen)%%>', $combo_regimen->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(regimen)%%>', $combo_regimen->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(regimen)%%>', urlencode($combo_regimen->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(eps)%%>', $combo_eps->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(eps)%%>', $combo_eps->MatchText, $templateCode);
	$templateCode = str_replace('<%%URLCOMBOTEXT(eps)%%>', urlencode($combo_eps->MatchText), $templateCode);
	$templateCode = str_replace('<%%COMBO(consulta)%%>', $combo_consulta->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(consulta)%%>', $combo_consulta->SelectedData, $templateCode);
	$templateCode = str_replace('<%%COMBO(fechaconsulta)%%>', ($selected_id && !$arrPerm[3] ? '<div class="form-control-static">' . $combo_fechaconsulta->GetHTML(true) . '</div>' : $combo_fechaconsulta->GetHTML()), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(fechaconsulta)%%>', $combo_fechaconsulta->GetHTML(true), $templateCode);
	$templateCode = str_replace('<%%COMBO(prueba)%%>', $combo_prueba->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(prueba)%%>', $combo_prueba->SelectedData, $templateCode);
	$templateCode = str_replace('<%%COMBO(fechaprueba)%%>', ($selected_id && !$arrPerm[3] ? '<div class="form-control-static">' . $combo_fechaprueba->GetHTML(true) . '</div>' : $combo_fechaprueba->GetHTML()), $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(fechaprueba)%%>', $combo_fechaprueba->GetHTML(true), $templateCode);
	$templateCode = str_replace('<%%COMBO(estado)%%>', $combo_estado->HTML, $templateCode);
	$templateCode = str_replace('<%%COMBOTEXT(estado)%%>', $combo_estado->SelectedData, $templateCode);

	/* lookup fields array: 'lookup field name' => array('parent table name', 'lookup field caption') */
	$lookup_fields = array('regimen' => array('regimenes', 'Regimen'), 'eps' => array('eps', 'Eps'), );
	foreach($lookup_fields as $luf => $ptfc) {
		$pt_perm = getTablePermissions($ptfc[0]);

		// process foreign key links
		if($pt_perm['view'] || $pt_perm['edit']) {
			$templateCode = str_replace("<%%PLINK({$luf})%%>", '<button type="button" class="btn btn-default view_parent hspacer-md" id="' . $ptfc[0] . '_view_parent" title="' . html_attr($Translation['View'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-eye-open"></i></button>', $templateCode);
		}

		// if user has insert permission to parent table of a lookup field, put an add new button
		if($pt_perm['insert'] /* && !$_REQUEST['Embedded']*/) {
			$templateCode = str_replace("<%%ADDNEW({$ptfc[0]})%%>", '<button type="button" class="btn btn-success add_new_parent hspacer-md" id="' . $ptfc[0] . '_add_new" title="' . html_attr($Translation['Add New'] . ' ' . $ptfc[1]) . '"><i class="glyphicon glyphicon-plus-sign"></i></button>', $templateCode);
		}
	}

	// process images
	$templateCode = str_replace('<%%UPLOADFILE(id)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(fecha)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(documento)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(nombrepaciente)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(regimen)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(eps)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(direccion)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(telefono)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(consulta)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(fechaconsulta)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(prueba)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(fechaprueba)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(estado)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(observacion)%%>', '', $templateCode);
	$templateCode = str_replace('<%%UPLOADFILE(encargado)%%>', '', $templateCode);

	// process values
	if($selected_id) {
		if( $dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', safe_html($urow['id']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(id)%%>', html_attr($row['id']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode($urow['id']), $templateCode);
		$templateCode = str_replace('<%%VALUE(fecha)%%>', @date('d/m/Y', @strtotime(html_attr($row['fecha']))), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fecha)%%>', urlencode(@date('d/m/Y', @strtotime(html_attr($urow['fecha'])))), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(documento)%%>', safe_html($urow['documento']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(documento)%%>', html_attr($row['documento']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(documento)%%>', urlencode($urow['documento']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(nombrepaciente)%%>', safe_html($urow['nombrepaciente']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(nombrepaciente)%%>', html_attr($row['nombrepaciente']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(nombrepaciente)%%>', urlencode($urow['nombrepaciente']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(regimen)%%>', safe_html($urow['regimen']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(regimen)%%>', html_attr($row['regimen']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(regimen)%%>', urlencode($urow['regimen']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(eps)%%>', safe_html($urow['eps']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(eps)%%>', html_attr($row['eps']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(eps)%%>', urlencode($urow['eps']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(direccion)%%>', safe_html($urow['direccion']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(direccion)%%>', html_attr($row['direccion']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(direccion)%%>', urlencode($urow['direccion']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(telefono)%%>', safe_html($urow['telefono']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(telefono)%%>', html_attr($row['telefono']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(telefono)%%>', urlencode($urow['telefono']), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(consulta)%%>', safe_html($urow['consulta']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(consulta)%%>', html_attr($row['consulta']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(consulta)%%>', urlencode($urow['consulta']), $templateCode);
		$templateCode = str_replace('<%%VALUE(fechaconsulta)%%>', @date('d/m/Y', @strtotime(html_attr($row['fechaconsulta']))), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fechaconsulta)%%>', urlencode(@date('d/m/Y', @strtotime(html_attr($urow['fechaconsulta'])))), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(prueba)%%>', safe_html($urow['prueba']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(prueba)%%>', html_attr($row['prueba']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(prueba)%%>', urlencode($urow['prueba']), $templateCode);
		$templateCode = str_replace('<%%VALUE(fechaprueba)%%>', @date('d/m/Y', @strtotime(html_attr($row['fechaprueba']))), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fechaprueba)%%>', urlencode(@date('d/m/Y', @strtotime(html_attr($urow['fechaprueba'])))), $templateCode);
		if( $dvprint) $templateCode = str_replace('<%%VALUE(estado)%%>', safe_html($urow['estado']), $templateCode);
		if(!$dvprint) $templateCode = str_replace('<%%VALUE(estado)%%>', html_attr($row['estado']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(estado)%%>', urlencode($urow['estado']), $templateCode);
		if($dvprint || (!$AllowUpdate && !$AllowInsert)) {
			$templateCode = str_replace('<%%VALUE(observacion)%%>', safe_html($urow['observacion']), $templateCode);
		} else {
			$templateCode = str_replace('<%%VALUE(observacion)%%>', safe_html($urow['observacion'], true), $templateCode);
		}
		$templateCode = str_replace('<%%URLVALUE(observacion)%%>', urlencode($urow['observacion']), $templateCode);
		$templateCode = str_replace('<%%VALUE(encargado)%%>', safe_html($urow['encargado']), $templateCode);
		$templateCode = str_replace('<%%URLVALUE(encargado)%%>', urlencode($urow['encargado']), $templateCode);
	} else {
		$templateCode = str_replace('<%%VALUE(id)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(id)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(fecha)%%>', '<%%editingDate%%>', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fecha)%%>', urlencode('<%%editingDate%%>'), $templateCode);
		$templateCode = str_replace('<%%VALUE(documento)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(documento)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(nombrepaciente)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(nombrepaciente)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(regimen)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(regimen)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(eps)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(eps)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(direccion)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(direccion)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(telefono)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(telefono)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(consulta)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(consulta)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(fechaconsulta)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fechaconsulta)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(prueba)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(prueba)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(fechaprueba)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(fechaprueba)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(estado)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(estado)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(observacion)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(observacion)%%>', urlencode(''), $templateCode);
		$templateCode = str_replace('<%%VALUE(encargado)%%>', '', $templateCode);
		$templateCode = str_replace('<%%URLVALUE(encargado)%%>', urlencode(''), $templateCode);
	}

	// process translations
	$templateCode = parseTemplate($templateCode);

	// clear scrap
	$templateCode = str_replace('<%%', '<!-- ', $templateCode);
	$templateCode = str_replace('%%>', ' -->', $templateCode);

	// hide links to inaccessible tables
	if($_REQUEST['dvprint_x'] == '') {
		$templateCode .= "\n\n<script>\$j(function() {\n";
		$arrTables = getTableList();
		foreach($arrTables as $name => $caption) {
			$templateCode .= "\t\$j('#{$name}_link').removeClass('hidden');\n";
			$templateCode .= "\t\$j('#xs_{$name}_link').removeClass('hidden');\n";
		}

		$templateCode .= $jsReadOnly;
		$templateCode .= $jsEditable;

		if(!$selected_id) {
		}

		$templateCode.="\n});</script>\n";
	}

	// ajaxed auto-fill fields
	$templateCode .= '<script>';
	$templateCode .= '$j(function() {';


	$templateCode.="});";
	$templateCode.="</script>";
	$templateCode .= $lookups;

	// handle enforced parent values for read-only lookup fields

	// don't include blank images in lightbox gallery
	$templateCode = preg_replace('/blank.gif" data-lightbox=".*?"/', 'blank.gif"', $templateCode);

	// don't display empty email links
	$templateCode=preg_replace('/<a .*?href="mailto:".*?<\/a>/', '', $templateCode);

	/* default field values */
	$rdata = $jdata = get_defaults('prass');
	if($selected_id) {
		$jdata = get_joined_record('prass', $selected_id);
		if($jdata === false) $jdata = get_defaults('prass');
		$rdata = $row;
	}
	$templateCode .= loadView('prass-ajax-cache', array('rdata' => $rdata, 'jdata' => $jdata));

	// hook: prass_dv
	if(function_exists('prass_dv')) {
		$args=[];
		prass_dv(($selected_id ? $selected_id : FALSE), getMemberInfo(), $templateCode, $args);
	}

	return $templateCode;
}