<?php
// This script and data application were generated by AppGini 5.97
// Download AppGini for free from https://bigprof.com/appgini/download/

	$currDir = dirname(__FILE__);
	include_once("{$currDir}/lib.php");
	@include_once("{$currDir}/hooks/soportes.php");
	include_once("{$currDir}/soportes_dml.php");

	// mm: can the current member access this page?
	$perm = getTablePermissions('soportes');
	if(!$perm['access']) {
		echo error_message($Translation['tableAccessDenied']);
		exit;
	}

	$x = new DataList;
	$x->TableName = 'soportes';

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV = [
		"`soportes`.`id`" => "id",
		"IF(    CHAR_LENGTH(`pqr1`.`doc`), CONCAT_WS('',   `pqr1`.`doc`), '') /* Documento */" => "doc",
		"`soportes`.`soporte1`" => "soporte1",
		"`soportes`.`soporte2`" => "soporte2",
		"`soportes`.`soporte3`" => "soporte3",
		"`soportes`.`soporte4`" => "soporte4",
	];
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = [
		1 => '`soportes`.`id`',
		2 => '`pqr1`.`doc`',
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
	];

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV = [
		"`soportes`.`id`" => "id",
		"IF(    CHAR_LENGTH(`pqr1`.`doc`), CONCAT_WS('',   `pqr1`.`doc`), '') /* Documento */" => "doc",
		"`soportes`.`soporte1`" => "soporte1",
		"`soportes`.`soporte2`" => "soporte2",
		"`soportes`.`soporte3`" => "soporte3",
		"`soportes`.`soporte4`" => "soporte4",
	];
	// Fields that can be filtered
	$x->QueryFieldsFilters = [
		"`soportes`.`id`" => "ID",
		"IF(    CHAR_LENGTH(`pqr1`.`doc`), CONCAT_WS('',   `pqr1`.`doc`), '') /* Documento */" => "Documento",
		"`soportes`.`soporte1`" => "Soporte 1",
		"`soportes`.`soporte2`" => "Soporte 2",
		"`soportes`.`soporte3`" => "Soporte 3",
		"`soportes`.`soporte4`" => "Soporte 4",
	];

	// Fields that can be quick searched
	$x->QueryFieldsQS = [
		"`soportes`.`id`" => "id",
		"IF(    CHAR_LENGTH(`pqr1`.`doc`), CONCAT_WS('',   `pqr1`.`doc`), '') /* Documento */" => "doc",
		"`soportes`.`soporte1`" => "soporte1",
		"`soportes`.`soporte2`" => "soporte2",
		"`soportes`.`soporte3`" => "soporte3",
		"`soportes`.`soporte4`" => "soporte4",
	];

	// Lookup fields that can be used as filterers
	$x->filterers = ['doc' => 'Documento', ];

	$x->QueryFrom = "`soportes` LEFT JOIN `pqr` as pqr1 ON `pqr1`.`id`=`soportes`.`doc` ";
	$x->QueryWhere = '';
	$x->QueryOrder = '';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm['view'] == 0 ? 1 : 0);
	$x->AllowDelete = $perm['delete'];
	$x->AllowMassDelete = (getLoggedAdmin() !== false);
	$x->AllowInsert = $perm['insert'];
	$x->AllowUpdate = $perm['edit'];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = (getLoggedAdmin() !== false);
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowPrintingDV = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation['quick search'];
	$x->ScriptFileName = 'soportes_view.php';
	$x->RedirectAfterInsert = 'soportes_view.php?SelectedID=#ID#';
	$x->TableTitle = 'Soportes';
	$x->TableIcon = 'resources/table_icons/file_extension_dat.png';
	$x->PrimaryKey = '`soportes`.`id`';

	$x->ColWidth = [150, 150, 150, 150, 150, ];
	$x->ColCaption = ['Documento', 'Soporte 1', 'Soporte 2', 'Soporte 3', 'Soporte 4', ];
	$x->ColFieldName = ['doc', 'soporte1', 'soporte2', 'soporte3', 'soporte4', ];
	$x->ColNumber  = [2, 3, 4, 5, 6, ];

	// template paths below are based on the app main directory
	$x->Template = 'templates/soportes_templateTV.html';
	$x->SelectedTemplate = 'templates/soportes_templateTVS.html';
	$x->TemplateDV = 'templates/soportes_templateDV.html';
	$x->TemplateDVP = 'templates/soportes_templateDVP.html';

	$x->ShowTableHeader = 1;
	$x->TVClasses = "";
	$x->DVClasses = "";
	$x->HasCalculatedFields = false;
	$x->AllowConsoleLog = false;
	$x->AllowDVNavigation = true;

	// hook: soportes_init
	$render = true;
	if(function_exists('soportes_init')) {
		$args = [];
		$render = soportes_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: soportes_header
	$headerCode = '';
	if(function_exists('soportes_header')) {
		$args = [];
		$headerCode = soportes_header($x->ContentType, getMemberInfo(), $args);
	}

	if(!$headerCode) {
		include_once("{$currDir}/header.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/header.php");
		echo str_replace('<%%HEADER%%>', ob_get_clean(), $headerCode);
	}

	echo $x->HTML;

	// hook: soportes_footer
	$footerCode = '';
	if(function_exists('soportes_footer')) {
		$args = [];
		$footerCode = soportes_footer($x->ContentType, getMemberInfo(), $args);
	}

	if(!$footerCode) {
		include_once("{$currDir}/footer.php"); 
	} else {
		ob_start();
		include_once("{$currDir}/footer.php");
		echo str_replace('<%%FOOTER%%>', ob_get_clean(), $footerCode);
	}
