<?php

	// IMPORTANT:
	// ==========
	// When translating, only translate the strings that are
	// TO THE RIGHT OF the arrow sign (=>).
	//
	// Do NOT translate the strings between square brackets ([]) or (<>)
	// =====================================================
	$ReportTranslation = array(
		'back' => "Atrás",
		'print report' => "Imprimir Reporte",
		'export report to csv file' => "Exportar informe a archivo CSV",
		'records' => "<n> registros",
		'from to' => "desde <FROM> hasta <TO>",
		'period from to' => "Periodo desde <FROM> hasta <TO>",
		'change' => "Cambiar",
		'report configuration' => "Configuración de informes",
		'report period' => "Periodo de informe",
		'month to date' => "Mes hasta la fecha",
		'month to date description' => 'Incluya datos del mes hasta la fecha. Compare con el mismo período el mes pasado y el mismo período el año pasado.',
		'current month' => "Mes actual",
		'current month description' => 'Incluya datos de todo el mes actual. Compare con el mes pasado y el mismo mes del año pasado.',
		'last month' => "El mes pasado",
		'last month description' => 'Incluya datos del mes pasado. Compare con el mes anterior y el mismo mes del año pasado.',
		'quarter to date' => "Trimestre hasta la fecha",
		'quarter to date description' => 'Incluya datos del trimestre hasta la fecha. Compare con el mismo período el trimestre pasado y el mismo período el año pasado.',
		'current quarter' => "Trimestre actual",
		'current quarter description' => 'Incluya datos del trimestre actual. Compare con el último y el mismo trimestre del año pasado.',
		'last quarter' => "Último cuarto",
		'last quarter description' => 'Incluya datos del último trimestre. Compare con el trimestre anterior y el mismo trimestre del año pasado.',
		'year to date' => "El año hasta la fecha",
		'year to date description' => 'Incluya datos del año hasta la fecha. Compare con el mismo período del año pasado y el mismo período del año anterior.',
		'current year' => "Año Actual",
		'current year description' => 'Incluya datos del año actual. Compare con el año pasado y el año anterior.',
		'last year' => "Ultimo año",
		'last year description' => 'Incluya datos del año pasado. Compare con los dos años anteriores.',
		'comparison period 1' => "Período de comparación 1",
		'comparison period 2' => "Período de comparación 2",
		'from' => "Desde",
		'to' => "Hasta",
		'order by' => "Ordenar por",
		'descending' => "Descendiente",
		'ascending' => "Ascendiente",
		'appearance' => "Apariencia (se aplica instantáneamente)",
		'show row numbers' => "Mostrar números de fila",
		'alignment of label column' => "Alineación de la columna <LABEL>",
		'alignment of other columns' => "Alineación de otras columnas",
		'apply' => "Aplicar",
		'close' => "Cerrar",
		'charts-color-theme' => 'Tema de color de gráficos',
		'rainbow' => 'Acoiris',
		'reds' => 'Gama de Rojos',
		'oranges' => 'Gama de Naranjas',
		'yellows' => 'Gama de Amarillos',
		'greens' => 'Gama de Verdes',
		'blues' => 'Gama de Azules',
		'violets' => 'Gama de Violetas',
		'grays' => 'Gama de grises',
		'barchart-orientation' => 'Orientación del gráfico de barras',
		'barchart-aspect-ratio' => 'Relación de aspecto del gráfico de barras (alto: ancho) ',
		'barchart-bar-width' => 'Ancho de barras en el gráfico de barras (píxeles)',
		'barchart-bar-spacing' => 'Espaciado de barras en el gráfico de barras (píxeles)',
		'barchart-bar-width-default-hint' => 'Un valor de 0 (el predeterminado) establece el ancho de la barra automáticamente.',
		'barchart-width' => 'Ancho del gráfico de barras',
		'piechart-width' => 'Ancho de gráficos circulares',
		'piechart-labels' => 'Etiquetas en gráficos circulares',
		'labels' => 'Etiquetas',
		'labels-values' => 'Etiquetas y valores',
		'labels-percentages' => 'Etiquetas y porcentajes',
		'labels-values-percentages' => 'Etiquetas, valores y porcentajes',
		'automatic' => 'Automatico',
		'loading report header' => 'Cargando encabezado del informe ...',
		'loading report footer' => 'Cargando pie de página del informe ...',
		'no-report-data' => 'No se encontraron datos para este informe o no tiene permisos suficientes.',
	);